<%
/************************************************************************************
Generated by AIDesigner 5.6.0.3
************************************************************************************
보고서 제목 : 통계
작성일 : 2016년4월22일 10시42분9초
수정일 : 2016년8월16일 14시30분12초
작성자 :
************************************************************************************/
%>

<%@ page pageEncoding="UTF-8" %>
<%@ page contentType="text/html; charset=utf-8" %>

<%@ page import="java.sql.*,java.io.*,java.lang.*,java.text.*,java.util.*,java.net.URL" %>
<%@ page import="com.activeintra.manager.*" %>
<%@ page import="com.activeintra.url.*" %>
<%@ page import="com.activeintra.util.uds.*" %>
<%@ page import="org.apache.log4j.Logger" %>
<%@ page import="org.apache.log4j.PropertyConfigurator" %>


<%
Object[] userObj = null;
HttpParameterDecoder decoder = HttpParameterDecoder.newInstance(request, application);
request.setAttribute("paramsDecoder", decoder);

String reportMode = decoder.getParameter("reportMode");
String reportParams = decoder.getParameter("reportParams");
if(reportMode!=null){
	if(reportMode.equals("PDF")){
		if(reportParams == null || reportParams.toLowerCase().indexOf("pdfserversave:true") == -1){
			out.clear();
			out=pageContext.pushBody();
		}
	}
	else if(reportMode.equals("EXCEL")){
		if(reportParams == null || reportParams.toLowerCase().indexOf("excelserversave:true") == -1){
			out.clear();
			out=pageContext.pushBody();
		}
	}
	else if(reportMode.equals("AR5")){
		out.clear();
		out=pageContext.pushBody();
	}
}

ReportHandler handler = new ReportHandler(pageContext, request, response, userObj, decoder);
handler.service(out);
handler = null;
%>

<%!
private ReportInitializer initializer;
//보고서 초기화 - 한번만 실행되고 사용자 Request에서 반복사용가능한 코드를 기술
public void jspInit() {
	initializer = new ReportInitializer(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
	//수정되지 않는 정적 Query변수들을 초기화
	//sql_getJnspJipPatentDate
	StringBuilder sql_getJnspJipPatentDate = new StringBuilder();
	sql_getJnspJipPatentDate.setLength(0);
	sql_getJnspJipPatentDate.append("SELECT ");
	sql_getJnspJipPatentDate.append("				A.IDX, ");
	sql_getJnspJipPatentDate.append("				A.ORG_NM , ");
	sql_getJnspJipPatentDate.append("				A.ORG_GRP_CD, ");
	sql_getJnspJipPatentDate.append("				DATE_FORMAT(A.SEARCH_DAY,'%Y년') AS AREA, ");
	sql_getJnspJipPatentDate.append("				COUNT(0) AS CNT ");
	sql_getJnspJipPatentDate.append("			FROM( ");
	sql_getJnspJipPatentDate.append("				SELECT ");
	sql_getJnspJipPatentDate.append("					'1' AS IDX , ");
	sql_getJnspJipPatentDate.append("					INTRL_APLC_NO AS APLC_NO, ");
	sql_getJnspJipPatentDate.append("					INTRL_APLC_DT AS SEARCH_DAY, ");
	sql_getJnspJipPatentDate.append("					OWN_ORG_NM AS ORG_NM, ");
	sql_getJnspJipPatentDate.append("					ORG_GRP_CD AS ORG_GRP_CD, ");
	sql_getJnspJipPatentDate.append("					STATE AS STATE ");
	sql_getJnspJipPatentDate.append("				FROM TB_SEARCH_BRAND ");
	sql_getJnspJipPatentDate.append("				UNION ALL ");
	sql_getJnspJipPatentDate.append("				SELECT ");
	sql_getJnspJipPatentDate.append("					'2' AS IDX , ");
	sql_getJnspJipPatentDate.append("					APLC_NO AS APLC_NO, ");
	sql_getJnspJipPatentDate.append("					APLC_DT AS SEARCH_DAY, ");
	sql_getJnspJipPatentDate.append("					OWN_ORG_NM AS ORG_NM, ");
	sql_getJnspJipPatentDate.append("					ORG_GRP_CD AS ORG_GRP_CD, ");
	sql_getJnspJipPatentDate.append("					STATE AS STATE ");
	sql_getJnspJipPatentDate.append("				FROM TB_SEARCH_DESIGN ");
	sql_getJnspJipPatentDate.append("				UNION ALL ");
	sql_getJnspJipPatentDate.append("				SELECT ");
	sql_getJnspJipPatentDate.append("					'3' AS IDX , ");
	sql_getJnspJipPatentDate.append("					KNOW_HOW_NO AS APLC_NO, ");
	sql_getJnspJipPatentDate.append("					REG_DT AS SEARCH_DAY, ");
	sql_getJnspJipPatentDate.append("					ORG_NM AS ORG_NM, ");
	sql_getJnspJipPatentDate.append("					ORG_GRP_CD AS ORG_GRP_CD, ");
	sql_getJnspJipPatentDate.append("					STATE AS STATE ");
	sql_getJnspJipPatentDate.append("				FROM TB_SEARCH_KNOW_HOW ");
	sql_getJnspJipPatentDate.append("				UNION ALL ");
	sql_getJnspJipPatentDate.append("				SELECT ");
	sql_getJnspJipPatentDate.append("					'4' AS IDX , ");
	sql_getJnspJipPatentDate.append("					APLC_NO AS APLC_NO, ");
	sql_getJnspJipPatentDate.append("					APLC_DT AS SEARCH_DAY, ");
	sql_getJnspJipPatentDate.append("					OWN_ORG_NM AS ORG_NM, ");
	sql_getJnspJipPatentDate.append("					ORG_GRP_CD AS ORG_GRP_CD, ");
	sql_getJnspJipPatentDate.append("					STATE AS STATE ");
	sql_getJnspJipPatentDate.append("				FROM TB_SEARCH_PATENT_UTILITY_MODEL ");
	sql_getJnspJipPatentDate.append("				UNION ALL ");
	sql_getJnspJipPatentDate.append("				SELECT ");
	sql_getJnspJipPatentDate.append("					'5' AS IDX , ");
	sql_getJnspJipPatentDate.append("					REG_NO AS APLC_NO, ");
	sql_getJnspJipPatentDate.append("					REG_DE AS SEARCH_DAY, ");
	sql_getJnspJipPatentDate.append("					OWN_ORG_NM AS ORG_NM, ");
	sql_getJnspJipPatentDate.append("					ORG_GRP_CD AS ORG_GRP_CD, ");
	sql_getJnspJipPatentDate.append("					STATE AS STATE ");
	sql_getJnspJipPatentDate.append("				FROM TB_SEARCH_PROGRAM ");
	sql_getJnspJipPatentDate.append("			) AS A ");
	sql_getJnspJipPatentDate.append("			LEFT JOIN TB_ORG_GRP AS B ");
	sql_getJnspJipPatentDate.append("			ON A.ORG_GRP_CD = B.ORG_GRP_CD ");
	sql_getJnspJipPatentDate.append("			WHERE 1 = 1 ");
	sql_getJnspJipPatentDate.append("			AND A.STATE = '2' ");
	sql_getJnspJipPatentDate.append("			AND B.AREA_CD = '1' ");
	sql_getJnspJipPatentDate.append("			AND A.IDX = '^Idx^' ");
	sql_getJnspJipPatentDate.append("			GROUP BY DATE_FORMAT(A.SEARCH_DAY,'%Y') ");
	sql_getJnspJipPatentDate.append("			ORDER BY DATE_FORMAT(A.SEARCH_DAY,'%Y') DESC ");
	sql_getJnspJipPatentDate.append("LIMIT 10 ");
	initializer.prepareQuery("sql_getJnspJipPatentDate", sql_getJnspJipPatentDate.toString());

	//sql_getJnspJipPatentDateTt
	StringBuilder sql_getJnspJipPatentDateTt = new StringBuilder();
	sql_getJnspJipPatentDateTt.setLength(0);
	sql_getJnspJipPatentDateTt.append("SELECT ");
	sql_getJnspJipPatentDateTt.append("				A.IDX, ");
	sql_getJnspJipPatentDateTt.append("				A.ORG_NM , ");
	sql_getJnspJipPatentDateTt.append("				A.ORG_GRP_CD, ");
	sql_getJnspJipPatentDateTt.append("				DATE_FORMAT(A.SEARCH_DAY,'%Y년') AS AREA, ");
	sql_getJnspJipPatentDateTt.append("				COUNT(0) AS CNT ");
	sql_getJnspJipPatentDateTt.append("			FROM( ");
	sql_getJnspJipPatentDateTt.append("				SELECT ");
	sql_getJnspJipPatentDateTt.append("					'1' AS IDX , ");
	sql_getJnspJipPatentDateTt.append("					INTRL_APLC_NO AS APLC_NO, ");
	sql_getJnspJipPatentDateTt.append("					INTRL_APLC_DT AS SEARCH_DAY, ");
	sql_getJnspJipPatentDateTt.append("					OWN_ORG_NM AS ORG_NM, ");
	sql_getJnspJipPatentDateTt.append("					ORG_GRP_CD AS ORG_GRP_CD, ");
	sql_getJnspJipPatentDateTt.append("					STATE AS STATE ");
	sql_getJnspJipPatentDateTt.append("				FROM TB_SEARCH_BRAND ");
	sql_getJnspJipPatentDateTt.append("				UNION ALL ");
	sql_getJnspJipPatentDateTt.append("				SELECT ");
	sql_getJnspJipPatentDateTt.append("					'2' AS IDX , ");
	sql_getJnspJipPatentDateTt.append("					APLC_NO AS APLC_NO, ");
	sql_getJnspJipPatentDateTt.append("					APLC_DT AS SEARCH_DAY, ");
	sql_getJnspJipPatentDateTt.append("					OWN_ORG_NM AS ORG_NM, ");
	sql_getJnspJipPatentDateTt.append("					ORG_GRP_CD AS ORG_GRP_CD, ");
	sql_getJnspJipPatentDateTt.append("					STATE AS STATE ");
	sql_getJnspJipPatentDateTt.append("				FROM TB_SEARCH_DESIGN ");
	sql_getJnspJipPatentDateTt.append("				UNION ALL ");
	sql_getJnspJipPatentDateTt.append("				SELECT ");
	sql_getJnspJipPatentDateTt.append("					'3' AS IDX , ");
	sql_getJnspJipPatentDateTt.append("					KNOW_HOW_NO AS APLC_NO, ");
	sql_getJnspJipPatentDateTt.append("					REG_DT AS SEARCH_DAY, ");
	sql_getJnspJipPatentDateTt.append("					ORG_NM AS ORG_NM, ");
	sql_getJnspJipPatentDateTt.append("					ORG_GRP_CD AS ORG_GRP_CD, ");
	sql_getJnspJipPatentDateTt.append("					STATE AS STATE ");
	sql_getJnspJipPatentDateTt.append("				FROM TB_SEARCH_KNOW_HOW ");
	sql_getJnspJipPatentDateTt.append("				UNION ALL ");
	sql_getJnspJipPatentDateTt.append("				SELECT ");
	sql_getJnspJipPatentDateTt.append("					'4' AS IDX , ");
	sql_getJnspJipPatentDateTt.append("					APLC_NO AS APLC_NO, ");
	sql_getJnspJipPatentDateTt.append("					APLC_DT AS SEARCH_DAY, ");
	sql_getJnspJipPatentDateTt.append("					OWN_ORG_NM AS ORG_NM, ");
	sql_getJnspJipPatentDateTt.append("					ORG_GRP_CD AS ORG_GRP_CD, ");
	sql_getJnspJipPatentDateTt.append("					STATE AS STATE ");
	sql_getJnspJipPatentDateTt.append("				FROM TB_SEARCH_PATENT_UTILITY_MODEL ");
	sql_getJnspJipPatentDateTt.append("				UNION ALL ");
	sql_getJnspJipPatentDateTt.append("				SELECT ");
	sql_getJnspJipPatentDateTt.append("					'5' AS IDX , ");
	sql_getJnspJipPatentDateTt.append("					REG_NO AS APLC_NO, ");
	sql_getJnspJipPatentDateTt.append("					REG_DE AS SEARCH_DAY, ");
	sql_getJnspJipPatentDateTt.append("					OWN_ORG_NM AS ORG_NM, ");
	sql_getJnspJipPatentDateTt.append("					ORG_GRP_CD AS ORG_GRP_CD, ");
	sql_getJnspJipPatentDateTt.append("					STATE AS STATE ");
	sql_getJnspJipPatentDateTt.append("				FROM TB_SEARCH_PROGRAM ");
	sql_getJnspJipPatentDateTt.append("			) AS A ");
	sql_getJnspJipPatentDateTt.append("			LEFT JOIN TB_ORG_GRP AS B ");
	sql_getJnspJipPatentDateTt.append("			ON A.ORG_GRP_CD = B.ORG_GRP_CD ");
	sql_getJnspJipPatentDateTt.append("			WHERE 1 = 1 ");
	sql_getJnspJipPatentDateTt.append("			AND A.STATE = '2' ");
	sql_getJnspJipPatentDateTt.append("			AND B.AREA_CD = '1' ");
	sql_getJnspJipPatentDateTt.append("			AND A.IDX = '^Idx^' ");
	sql_getJnspJipPatentDateTt.append("			GROUP BY DATE_FORMAT(A.SEARCH_DAY,'%Y') ");
	sql_getJnspJipPatentDateTt.append("			ORDER BY DATE_FORMAT(A.SEARCH_DAY,'%Y') DESC ");
	sql_getJnspJipPatentDateTt.append("LIMIT 10 ");
	initializer.prepareQuery("sql_getJnspJipPatentDateTt", sql_getJnspJipPatentDateTt.toString());

	//sql_getJnspJipPatentDateTb
	StringBuilder sql_getJnspJipPatentDateTb = new StringBuilder();
	sql_getJnspJipPatentDateTb.setLength(0);
	sql_getJnspJipPatentDateTb.append("SELECT ");
	sql_getJnspJipPatentDateTb.append("				A.IDX, ");
	sql_getJnspJipPatentDateTb.append("				A.ORG_NM , ");
	sql_getJnspJipPatentDateTb.append("				A.ORG_GRP_CD, ");
	sql_getJnspJipPatentDateTb.append("				DATE_FORMAT(A.SEARCH_DAY,'%Y년') AS AREA, ");
	sql_getJnspJipPatentDateTb.append("				COUNT(0) AS CNT ");
	sql_getJnspJipPatentDateTb.append("			FROM( ");
	sql_getJnspJipPatentDateTb.append("				SELECT ");
	sql_getJnspJipPatentDateTb.append("					'1' AS IDX , ");
	sql_getJnspJipPatentDateTb.append("					INTRL_APLC_NO AS APLC_NO, ");
	sql_getJnspJipPatentDateTb.append("					INTRL_APLC_DT AS SEARCH_DAY, ");
	sql_getJnspJipPatentDateTb.append("					OWN_ORG_NM AS ORG_NM, ");
	sql_getJnspJipPatentDateTb.append("					ORG_GRP_CD AS ORG_GRP_CD, ");
	sql_getJnspJipPatentDateTb.append("					STATE AS STATE ");
	sql_getJnspJipPatentDateTb.append("				FROM TB_SEARCH_BRAND ");
	sql_getJnspJipPatentDateTb.append("				UNION ALL ");
	sql_getJnspJipPatentDateTb.append("				SELECT ");
	sql_getJnspJipPatentDateTb.append("					'2' AS IDX , ");
	sql_getJnspJipPatentDateTb.append("					APLC_NO AS APLC_NO, ");
	sql_getJnspJipPatentDateTb.append("					APLC_DT AS SEARCH_DAY, ");
	sql_getJnspJipPatentDateTb.append("					OWN_ORG_NM AS ORG_NM, ");
	sql_getJnspJipPatentDateTb.append("					ORG_GRP_CD AS ORG_GRP_CD, ");
	sql_getJnspJipPatentDateTb.append("					STATE AS STATE ");
	sql_getJnspJipPatentDateTb.append("				FROM TB_SEARCH_DESIGN ");
	sql_getJnspJipPatentDateTb.append("				UNION ALL ");
	sql_getJnspJipPatentDateTb.append("				SELECT ");
	sql_getJnspJipPatentDateTb.append("					'3' AS IDX , ");
	sql_getJnspJipPatentDateTb.append("					KNOW_HOW_NO AS APLC_NO, ");
	sql_getJnspJipPatentDateTb.append("					REG_DT AS SEARCH_DAY, ");
	sql_getJnspJipPatentDateTb.append("					ORG_NM AS ORG_NM, ");
	sql_getJnspJipPatentDateTb.append("					ORG_GRP_CD AS ORG_GRP_CD, ");
	sql_getJnspJipPatentDateTb.append("					STATE AS STATE ");
	sql_getJnspJipPatentDateTb.append("				FROM TB_SEARCH_KNOW_HOW ");
	sql_getJnspJipPatentDateTb.append("				UNION ALL ");
	sql_getJnspJipPatentDateTb.append("				SELECT ");
	sql_getJnspJipPatentDateTb.append("					'4' AS IDX , ");
	sql_getJnspJipPatentDateTb.append("					APLC_NO AS APLC_NO, ");
	sql_getJnspJipPatentDateTb.append("					APLC_DT AS SEARCH_DAY, ");
	sql_getJnspJipPatentDateTb.append("					OWN_ORG_NM AS ORG_NM, ");
	sql_getJnspJipPatentDateTb.append("					ORG_GRP_CD AS ORG_GRP_CD, ");
	sql_getJnspJipPatentDateTb.append("					STATE AS STATE ");
	sql_getJnspJipPatentDateTb.append("				FROM TB_SEARCH_PATENT_UTILITY_MODEL ");
	sql_getJnspJipPatentDateTb.append("				UNION ALL ");
	sql_getJnspJipPatentDateTb.append("				SELECT ");
	sql_getJnspJipPatentDateTb.append("					'5' AS IDX , ");
	sql_getJnspJipPatentDateTb.append("					REG_NO AS APLC_NO, ");
	sql_getJnspJipPatentDateTb.append("					REG_DE AS SEARCH_DAY, ");
	sql_getJnspJipPatentDateTb.append("					OWN_ORG_NM AS ORG_NM, ");
	sql_getJnspJipPatentDateTb.append("					ORG_GRP_CD AS ORG_GRP_CD, ");
	sql_getJnspJipPatentDateTb.append("					STATE AS STATE ");
	sql_getJnspJipPatentDateTb.append("				FROM TB_SEARCH_PROGRAM ");
	sql_getJnspJipPatentDateTb.append("			) AS A ");
	sql_getJnspJipPatentDateTb.append("			LEFT JOIN TB_ORG_GRP AS B ");
	sql_getJnspJipPatentDateTb.append("			ON A.ORG_GRP_CD = B.ORG_GRP_CD ");
	sql_getJnspJipPatentDateTb.append("			WHERE 1 = 1 ");
	sql_getJnspJipPatentDateTb.append("			AND A.STATE = '2' ");
	sql_getJnspJipPatentDateTb.append("			AND B.AREA_CD = '1' ");
	sql_getJnspJipPatentDateTb.append("			AND A.IDX = '^Idx^' ");
	sql_getJnspJipPatentDateTb.append("			GROUP BY DATE_FORMAT(A.SEARCH_DAY,'%Y') ");
	sql_getJnspJipPatentDateTb.append("			ORDER BY DATE_FORMAT(A.SEARCH_DAY,'%Y') DESC ");
	initializer.prepareQuery("sql_getJnspJipPatentDateTb", sql_getJnspJipPatentDateTb.toString());

	//sql_getJnspJipPrevOrg
	StringBuilder sql_getJnspJipPrevOrg = new StringBuilder();
	sql_getJnspJipPrevOrg.setLength(0);
	sql_getJnspJipPrevOrg.append("SELECT ");
	sql_getJnspJipPrevOrg.append("				A.ORG_GRP_CD, ");
	sql_getJnspJipPrevOrg.append("				A.ORG_GRP_NM AS AREA, ");
	sql_getJnspJipPrevOrg.append("			( ");
	sql_getJnspJipPrevOrg.append("				SELECT COUNT(0) FROM TB_JIP_USE_STATUS AS B1 ");
	sql_getJnspJipPrevOrg.append("				LEFT JOIN ");
	sql_getJnspJipPrevOrg.append("						TB_SEARCH_PATENT_UTILITY_MODEL C1 ");
	sql_getJnspJipPrevOrg.append("					ON	B1.REGIST_INFO = C1.APLC_NO ");
	sql_getJnspJipPrevOrg.append("				LEFT JOIN ");
	sql_getJnspJipPrevOrg.append("						TB_SEARCH_DESIGN D1 ");
	sql_getJnspJipPrevOrg.append("					ON	B1.REGIST_INFO = D1.APLC_NO ");
	sql_getJnspJipPrevOrg.append("				LEFT JOIN ");
	sql_getJnspJipPrevOrg.append("						TB_SEARCH_BRAND E1 ");
	sql_getJnspJipPrevOrg.append("					ON	B1.REGIST_INFO = E1.INTRL_APLC_NO ");
	sql_getJnspJipPrevOrg.append("				LEFT JOIN ");
	sql_getJnspJipPrevOrg.append("						TB_SEARCH_PROGRAM F1 ");
	sql_getJnspJipPrevOrg.append("					ON	B1.REGIST_INFO = F1.REG_NO ");
	sql_getJnspJipPrevOrg.append("				LEFT JOIN ");
	sql_getJnspJipPrevOrg.append("						TB_SEARCH_KNOW_HOW G1 ");
	sql_getJnspJipPrevOrg.append("					ON	B1.REGIST_INFO = G1.KNOW_HOW_NO ");
	sql_getJnspJipPrevOrg.append("				WHERE B1.STATE = '2' ");
	sql_getJnspJipPrevOrg.append("				AND A.ORG_GRP_CD = B1.ORG_GRP_CD ");
	sql_getJnspJipPrevOrg.append("			) AS CNT ");
	sql_getJnspJipPrevOrg.append("			FROM ");
	sql_getJnspJipPrevOrg.append("			TB_ORG_GRP AS A ");
	sql_getJnspJipPrevOrg.append("			WHERE (A.DELETE_YN != 'Y' OR A.DELETE_YN IS NULL) ");
	sql_getJnspJipPrevOrg.append("			AND A.APPLY_CD = '20' ");
	sql_getJnspJipPrevOrg.append("			ORDER BY CNT DESC ");
	sql_getJnspJipPrevOrg.append("LIMIT 10 ");
	initializer.prepareQuery("sql_getJnspJipPrevOrg", sql_getJnspJipPrevOrg.toString());

	//sql_getJnspJipPrevOrgTt
	StringBuilder sql_getJnspJipPrevOrgTt = new StringBuilder();
	sql_getJnspJipPrevOrgTt.setLength(0);
	sql_getJnspJipPrevOrgTt.append("SELECT ");
	sql_getJnspJipPrevOrgTt.append("				A.ORG_GRP_CD, ");
	sql_getJnspJipPrevOrgTt.append("				A.ORG_GRP_NM AS AREA, ");
	sql_getJnspJipPrevOrgTt.append("			( ");
	sql_getJnspJipPrevOrgTt.append("				SELECT COUNT(0) FROM TB_JIP_USE_STATUS AS B1 ");
	sql_getJnspJipPrevOrgTt.append("				LEFT JOIN ");
	sql_getJnspJipPrevOrgTt.append("						TB_SEARCH_PATENT_UTILITY_MODEL C1 ");
	sql_getJnspJipPrevOrgTt.append("					ON	B1.REGIST_INFO = C1.APLC_NO ");
	sql_getJnspJipPrevOrgTt.append("				LEFT JOIN ");
	sql_getJnspJipPrevOrgTt.append("						TB_SEARCH_DESIGN D1 ");
	sql_getJnspJipPrevOrgTt.append("					ON	B1.REGIST_INFO = D1.APLC_NO ");
	sql_getJnspJipPrevOrgTt.append("				LEFT JOIN ");
	sql_getJnspJipPrevOrgTt.append("						TB_SEARCH_BRAND E1 ");
	sql_getJnspJipPrevOrgTt.append("					ON	B1.REGIST_INFO = E1.INTRL_APLC_NO ");
	sql_getJnspJipPrevOrgTt.append("				LEFT JOIN ");
	sql_getJnspJipPrevOrgTt.append("						TB_SEARCH_PROGRAM F1 ");
	sql_getJnspJipPrevOrgTt.append("					ON	B1.REGIST_INFO = F1.REG_NO ");
	sql_getJnspJipPrevOrgTt.append("				LEFT JOIN ");
	sql_getJnspJipPrevOrgTt.append("						TB_SEARCH_KNOW_HOW G1 ");
	sql_getJnspJipPrevOrgTt.append("					ON	B1.REGIST_INFO = G1.KNOW_HOW_NO ");
	sql_getJnspJipPrevOrgTt.append("				WHERE B1.STATE = '2' ");
	sql_getJnspJipPrevOrgTt.append("				AND A.ORG_GRP_CD = B1.ORG_GRP_CD ");
	sql_getJnspJipPrevOrgTt.append("			) AS CNT ");
	sql_getJnspJipPrevOrgTt.append("			FROM ");
	sql_getJnspJipPrevOrgTt.append("			TB_ORG_GRP AS A ");
	sql_getJnspJipPrevOrgTt.append("			WHERE (A.DELETE_YN != 'Y' OR A.DELETE_YN IS NULL) ");
	sql_getJnspJipPrevOrgTt.append("			AND A.APPLY_CD = '20' ");
	sql_getJnspJipPrevOrgTt.append("			ORDER BY CNT DESC ");
	sql_getJnspJipPrevOrgTt.append("LIMIT 10 ");
	initializer.prepareQuery("sql_getJnspJipPrevOrgTt", sql_getJnspJipPrevOrgTt.toString());

	//sql_getJnspJipPrevOrgTb
	StringBuilder sql_getJnspJipPrevOrgTb = new StringBuilder();
	sql_getJnspJipPrevOrgTb.setLength(0);
	sql_getJnspJipPrevOrgTb.append("SELECT ");
	sql_getJnspJipPrevOrgTb.append("				A.ORG_GRP_CD, ");
	sql_getJnspJipPrevOrgTb.append("				A.ORG_GRP_NM AS AREA, ");
	sql_getJnspJipPrevOrgTb.append("			( ");
	sql_getJnspJipPrevOrgTb.append("				SELECT COUNT(0) FROM TB_JIP_USE_STATUS AS B1 ");
	sql_getJnspJipPrevOrgTb.append("				LEFT JOIN ");
	sql_getJnspJipPrevOrgTb.append("						TB_SEARCH_PATENT_UTILITY_MODEL C1 ");
	sql_getJnspJipPrevOrgTb.append("					ON	B1.REGIST_INFO = C1.APLC_NO ");
	sql_getJnspJipPrevOrgTb.append("				LEFT JOIN ");
	sql_getJnspJipPrevOrgTb.append("						TB_SEARCH_DESIGN D1 ");
	sql_getJnspJipPrevOrgTb.append("					ON	B1.REGIST_INFO = D1.APLC_NO ");
	sql_getJnspJipPrevOrgTb.append("				LEFT JOIN ");
	sql_getJnspJipPrevOrgTb.append("						TB_SEARCH_BRAND E1 ");
	sql_getJnspJipPrevOrgTb.append("					ON	B1.REGIST_INFO = E1.INTRL_APLC_NO ");
	sql_getJnspJipPrevOrgTb.append("				LEFT JOIN ");
	sql_getJnspJipPrevOrgTb.append("						TB_SEARCH_PROGRAM F1 ");
	sql_getJnspJipPrevOrgTb.append("					ON	B1.REGIST_INFO = F1.REG_NO ");
	sql_getJnspJipPrevOrgTb.append("				LEFT JOIN ");
	sql_getJnspJipPrevOrgTb.append("						TB_SEARCH_KNOW_HOW G1 ");
	sql_getJnspJipPrevOrgTb.append("					ON	B1.REGIST_INFO = G1.KNOW_HOW_NO ");
	sql_getJnspJipPrevOrgTb.append("				WHERE B1.STATE = '2' ");
	sql_getJnspJipPrevOrgTb.append("				AND A.ORG_GRP_CD = B1.ORG_GRP_CD ");
	sql_getJnspJipPrevOrgTb.append("			) AS CNT ");
	sql_getJnspJipPrevOrgTb.append("			FROM ");
	sql_getJnspJipPrevOrgTb.append("			TB_ORG_GRP AS A ");
	sql_getJnspJipPrevOrgTb.append("			WHERE (A.DELETE_YN != 'Y' OR A.DELETE_YN IS NULL) ");
	sql_getJnspJipPrevOrgTb.append("			AND A.APPLY_CD = '20' ");
	sql_getJnspJipPrevOrgTb.append("			ORDER BY CNT DESC ");
	initializer.prepareQuery("sql_getJnspJipPrevOrgTb", sql_getJnspJipPrevOrgTb.toString());

	//sql_getJnspJipPrevArea
	StringBuilder sql_getJnspJipPrevArea = new StringBuilder();
	sql_getJnspJipPrevArea.setLength(0);
	sql_getJnspJipPrevArea.append("SELECT ");
	sql_getJnspJipPrevArea.append("				A.ORG_GRP_CD, ");
	sql_getJnspJipPrevArea.append("				A.ORG_GRP_NM, ");
	sql_getJnspJipPrevArea.append("				C.CODE_NM AS AREA, ");
	sql_getJnspJipPrevArea.append("				IF( ISNULL(C.CODE_NM) , 0 , COUNT(0)) AS CNT ");
	sql_getJnspJipPrevArea.append("			FROM TB_ORG_GRP AS A ");
	sql_getJnspJipPrevArea.append("			LEFT JOIN TB_JIP_USE_STATUS AS B ");
	sql_getJnspJipPrevArea.append("			ON A.ORG_GRP_CD = B.ORG_GRP_CD ");
	sql_getJnspJipPrevArea.append("			LEFT JOIN TB_CODE AS C ");
	sql_getJnspJipPrevArea.append("			ON A.AREA_LOCATION_CD = C.CODE_CD ");
	sql_getJnspJipPrevArea.append("			WHERE A.ORG_GRP_CD = B.ORG_GRP_CD ");
	sql_getJnspJipPrevArea.append("			AND C.CODE_GRP_CD = 'AreaSigungu' ");
	sql_getJnspJipPrevArea.append("			AND A.AREA_CD = '1' ");
	sql_getJnspJipPrevArea.append("			AND A.ORG_TYPE = '2' ");
	sql_getJnspJipPrevArea.append("			AND (A.DELETE_YN != 'Y' OR A.DELETE_YN IS NULL) ");
	sql_getJnspJipPrevArea.append("			AND A.APPLY_CD = '20' ");
	sql_getJnspJipPrevArea.append("			GROUP BY C.CODE_NM ");
	sql_getJnspJipPrevArea.append("			ORDER BY CNT DESC ");
	sql_getJnspJipPrevArea.append("LIMIT 10 ");
	initializer.prepareQuery("sql_getJnspJipPrevArea", sql_getJnspJipPrevArea.toString());

	//sql_getJnspJipPrevAreaTt
	StringBuilder sql_getJnspJipPrevAreaTt = new StringBuilder();
	sql_getJnspJipPrevAreaTt.setLength(0);
	sql_getJnspJipPrevAreaTt.append("SELECT ");
	sql_getJnspJipPrevAreaTt.append("				A.ORG_GRP_CD, ");
	sql_getJnspJipPrevAreaTt.append("				A.ORG_GRP_NM, ");
	sql_getJnspJipPrevAreaTt.append("				C.CODE_NM AS AREA, ");
	sql_getJnspJipPrevAreaTt.append("				IF( ISNULL(C.CODE_NM) , 0 , COUNT(0)) AS CNT ");
	sql_getJnspJipPrevAreaTt.append("			FROM TB_ORG_GRP AS A ");
	sql_getJnspJipPrevAreaTt.append("			LEFT JOIN TB_JIP_USE_STATUS AS B ");
	sql_getJnspJipPrevAreaTt.append("			ON A.ORG_GRP_CD = B.ORG_GRP_CD ");
	sql_getJnspJipPrevAreaTt.append("			LEFT JOIN TB_CODE AS C ");
	sql_getJnspJipPrevAreaTt.append("			ON A.AREA_LOCATION_CD = C.CODE_CD ");
	sql_getJnspJipPrevAreaTt.append("			WHERE A.ORG_GRP_CD = B.ORG_GRP_CD ");
	sql_getJnspJipPrevAreaTt.append("			AND C.CODE_GRP_CD = 'AreaSigungu' ");
	sql_getJnspJipPrevAreaTt.append("			AND A.AREA_CD = '1' ");
	sql_getJnspJipPrevAreaTt.append("			AND A.ORG_TYPE = '2' ");
	sql_getJnspJipPrevAreaTt.append("			AND (A.DELETE_YN != 'Y' OR A.DELETE_YN IS NULL) ");
	sql_getJnspJipPrevAreaTt.append("			AND A.APPLY_CD = '20' ");
	sql_getJnspJipPrevAreaTt.append("			GROUP BY C.CODE_NM ");
	sql_getJnspJipPrevAreaTt.append("			ORDER BY CNT DESC ");
	sql_getJnspJipPrevAreaTt.append("LIMIT 10 ");
	initializer.prepareQuery("sql_getJnspJipPrevAreaTt", sql_getJnspJipPrevAreaTt.toString());

	//sql_getJnspJipPrevAreaTb
	StringBuilder sql_getJnspJipPrevAreaTb = new StringBuilder();
	sql_getJnspJipPrevAreaTb.setLength(0);
	sql_getJnspJipPrevAreaTb.append("SELECT ");
	sql_getJnspJipPrevAreaTb.append("				A.ORG_GRP_CD, ");
	sql_getJnspJipPrevAreaTb.append("				A.ORG_GRP_NM, ");
	sql_getJnspJipPrevAreaTb.append("				C.CODE_NM AS AREA, ");
	sql_getJnspJipPrevAreaTb.append("				IF( ISNULL(C.CODE_NM) , 0 , COUNT(0)) AS CNT ");
	sql_getJnspJipPrevAreaTb.append("			FROM TB_ORG_GRP AS A ");
	sql_getJnspJipPrevAreaTb.append("			LEFT JOIN TB_JIP_USE_STATUS AS B ");
	sql_getJnspJipPrevAreaTb.append("			ON A.ORG_GRP_CD = B.ORG_GRP_CD ");
	sql_getJnspJipPrevAreaTb.append("			LEFT JOIN TB_CODE AS C ");
	sql_getJnspJipPrevAreaTb.append("			ON A.AREA_LOCATION_CD = C.CODE_CD ");
	sql_getJnspJipPrevAreaTb.append("			WHERE A.ORG_GRP_CD = B.ORG_GRP_CD ");
	sql_getJnspJipPrevAreaTb.append("			AND C.CODE_GRP_CD = 'AreaSigungu' ");
	sql_getJnspJipPrevAreaTb.append("			AND A.AREA_CD = '1' ");
	sql_getJnspJipPrevAreaTb.append("			AND A.ORG_TYPE = '2' ");
	sql_getJnspJipPrevAreaTb.append("			AND (A.DELETE_YN != 'Y' OR A.DELETE_YN IS NULL) ");
	sql_getJnspJipPrevAreaTb.append("			AND A.APPLY_CD = '20' ");
	sql_getJnspJipPrevAreaTb.append("			GROUP BY C.CODE_NM ");
	sql_getJnspJipPrevAreaTb.append("			ORDER BY CNT DESC ");
	initializer.prepareQuery("sql_getJnspJipPrevAreaTb", sql_getJnspJipPrevAreaTb.toString());

	//sql_getJnspJipPrevYear
	StringBuilder sql_getJnspJipPrevYear = new StringBuilder();
	sql_getJnspJipPrevYear.setLength(0);
	sql_getJnspJipPrevYear.append("SELECT ");
	sql_getJnspJipPrevYear.append("				A.ORG_GRP_CD, ");
	sql_getJnspJipPrevYear.append("				A.ORG_GRP_NM , ");
	sql_getJnspJipPrevYear.append("				B.CODE_NM AS AREA, ");
	sql_getJnspJipPrevYear.append("				DATE_FORMAT(C.TRANSFER_DATE,'%Y년') AS DA, ");
	sql_getJnspJipPrevYear.append("			( ");
	sql_getJnspJipPrevYear.append("				SELECT COUNT(0) FROM TB_JIP_USE_STATUS AS B1 ");
	sql_getJnspJipPrevYear.append("				LEFT JOIN ");
	sql_getJnspJipPrevYear.append("						TB_SEARCH_PATENT_UTILITY_MODEL C1 ");
	sql_getJnspJipPrevYear.append("					ON	B1.REGIST_INFO = C1.APLC_NO ");
	sql_getJnspJipPrevYear.append("				LEFT JOIN ");
	sql_getJnspJipPrevYear.append("						TB_SEARCH_DESIGN D1 ");
	sql_getJnspJipPrevYear.append("					ON	B1.REGIST_INFO = D1.APLC_NO ");
	sql_getJnspJipPrevYear.append("				LEFT JOIN ");
	sql_getJnspJipPrevYear.append("						TB_SEARCH_BRAND E1 ");
	sql_getJnspJipPrevYear.append("					ON	B1.REGIST_INFO = E1.INTRL_APLC_NO ");
	sql_getJnspJipPrevYear.append("				LEFT JOIN ");
	sql_getJnspJipPrevYear.append("						TB_SEARCH_PROGRAM F1 ");
	sql_getJnspJipPrevYear.append("					ON	B1.REGIST_INFO = F1.REG_NO ");
	sql_getJnspJipPrevYear.append("				LEFT JOIN ");
	sql_getJnspJipPrevYear.append("						TB_SEARCH_KNOW_HOW G1 ");
	sql_getJnspJipPrevYear.append("					ON	B1.REGIST_INFO = G1.KNOW_HOW_NO ");
	sql_getJnspJipPrevYear.append("				WHERE B1.STATE = '2' ");
	sql_getJnspJipPrevYear.append("				AND A.ORG_GRP_CD = B1.ORG_GRP_CD ");
	sql_getJnspJipPrevYear.append("			) AS CNT ");
	sql_getJnspJipPrevYear.append("			FROM ");
	sql_getJnspJipPrevYear.append("			TB_ORG_GRP AS A ");
	sql_getJnspJipPrevYear.append("			LEFT JOIN TB_CODE AS B ");
	sql_getJnspJipPrevYear.append("			ON A.AREA_LOCATION_CD = B.CODE_CD ");
	sql_getJnspJipPrevYear.append("			LEFT JOIN TB_JIP_USE_STATUS AS C ");
	sql_getJnspJipPrevYear.append("			ON A.ORG_GRP_CD = C.ORG_GRP_CD ");
	sql_getJnspJipPrevYear.append("			WHERE (A.DELETE_YN != 'Y' OR A.DELETE_YN IS NULL) ");
	sql_getJnspJipPrevYear.append("			AND B.CODE_GRP_CD = 'AreaSigungu' ");
	sql_getJnspJipPrevYear.append("			AND A.APPLY_CD = '20' ");
	sql_getJnspJipPrevYear.append("			AND TO_DAYS(DATE_FORMAT(C.TRANSFER_DATE,'%Y-1-1')) <= TO_DAYS(NOW()) ");
	sql_getJnspJipPrevYear.append("			AND TO_DAYS(DATE_FORMAT(C.TRANSFER_DATE,'%Y-1-1')) >= TO_DAYS(NOW())-3650 ");
	sql_getJnspJipPrevYear.append("			GROUP BY DATE_FORMAT(C.TRANSFER_DATE,'%Y') ");
	sql_getJnspJipPrevYear.append("			ORDER BY DATE_FORMAT(C.TRANSFER_DATE,'%Y') DESC ");
	sql_getJnspJipPrevYear.append("LIMIT 10 ");
	initializer.prepareQuery("sql_getJnspJipPrevYear", sql_getJnspJipPrevYear.toString());

	//sql_getJnspJipPrevYearTt
	StringBuilder sql_getJnspJipPrevYearTt = new StringBuilder();
	sql_getJnspJipPrevYearTt.setLength(0);
	sql_getJnspJipPrevYearTt.append("SELECT ");
	sql_getJnspJipPrevYearTt.append("				A.ORG_GRP_CD, ");
	sql_getJnspJipPrevYearTt.append("				A.ORG_GRP_NM , ");
	sql_getJnspJipPrevYearTt.append("				B.CODE_NM AS AREA, ");
	sql_getJnspJipPrevYearTt.append("				DATE_FORMAT(C.TRANSFER_DATE,'%Y년') AS DA, ");
	sql_getJnspJipPrevYearTt.append("			( ");
	sql_getJnspJipPrevYearTt.append("				SELECT COUNT(0) FROM TB_JIP_USE_STATUS AS B1 ");
	sql_getJnspJipPrevYearTt.append("				LEFT JOIN ");
	sql_getJnspJipPrevYearTt.append("						TB_SEARCH_PATENT_UTILITY_MODEL C1 ");
	sql_getJnspJipPrevYearTt.append("					ON	B1.REGIST_INFO = C1.APLC_NO ");
	sql_getJnspJipPrevYearTt.append("				LEFT JOIN ");
	sql_getJnspJipPrevYearTt.append("						TB_SEARCH_DESIGN D1 ");
	sql_getJnspJipPrevYearTt.append("					ON	B1.REGIST_INFO = D1.APLC_NO ");
	sql_getJnspJipPrevYearTt.append("				LEFT JOIN ");
	sql_getJnspJipPrevYearTt.append("						TB_SEARCH_BRAND E1 ");
	sql_getJnspJipPrevYearTt.append("					ON	B1.REGIST_INFO = E1.INTRL_APLC_NO ");
	sql_getJnspJipPrevYearTt.append("				LEFT JOIN ");
	sql_getJnspJipPrevYearTt.append("						TB_SEARCH_PROGRAM F1 ");
	sql_getJnspJipPrevYearTt.append("					ON	B1.REGIST_INFO = F1.REG_NO ");
	sql_getJnspJipPrevYearTt.append("				LEFT JOIN ");
	sql_getJnspJipPrevYearTt.append("						TB_SEARCH_KNOW_HOW G1 ");
	sql_getJnspJipPrevYearTt.append("					ON	B1.REGIST_INFO = G1.KNOW_HOW_NO ");
	sql_getJnspJipPrevYearTt.append("				WHERE B1.STATE = '2' ");
	sql_getJnspJipPrevYearTt.append("				AND A.ORG_GRP_CD = B1.ORG_GRP_CD ");
	sql_getJnspJipPrevYearTt.append("			) AS CNT ");
	sql_getJnspJipPrevYearTt.append("			FROM ");
	sql_getJnspJipPrevYearTt.append("			TB_ORG_GRP AS A ");
	sql_getJnspJipPrevYearTt.append("			LEFT JOIN TB_CODE AS B ");
	sql_getJnspJipPrevYearTt.append("			ON A.AREA_LOCATION_CD = B.CODE_CD ");
	sql_getJnspJipPrevYearTt.append("			LEFT JOIN TB_JIP_USE_STATUS AS C ");
	sql_getJnspJipPrevYearTt.append("			ON A.ORG_GRP_CD = C.ORG_GRP_CD ");
	sql_getJnspJipPrevYearTt.append("			WHERE (A.DELETE_YN != 'Y' OR A.DELETE_YN IS NULL) ");
	sql_getJnspJipPrevYearTt.append("			AND B.CODE_GRP_CD = 'AreaSigungu' ");
	sql_getJnspJipPrevYearTt.append("			AND A.APPLY_CD = '20' ");
	sql_getJnspJipPrevYearTt.append("			AND TO_DAYS(DATE_FORMAT(C.TRANSFER_DATE,'%Y-1-1')) <= TO_DAYS(NOW()) ");
	sql_getJnspJipPrevYearTt.append("			AND TO_DAYS(DATE_FORMAT(C.TRANSFER_DATE,'%Y-1-1')) >= TO_DAYS(NOW())-3650 ");
	sql_getJnspJipPrevYearTt.append("			GROUP BY DATE_FORMAT(C.TRANSFER_DATE,'%Y') ");
	sql_getJnspJipPrevYearTt.append("			ORDER BY DATE_FORMAT(C.TRANSFER_DATE,'%Y') DESC ");
	sql_getJnspJipPrevYearTt.append("LIMIT 10 ");
	initializer.prepareQuery("sql_getJnspJipPrevYearTt", sql_getJnspJipPrevYearTt.toString());

	//sql_getJnspJipPrevYearTb
	StringBuilder sql_getJnspJipPrevYearTb = new StringBuilder();
	sql_getJnspJipPrevYearTb.setLength(0);
	sql_getJnspJipPrevYearTb.append("SELECT ");
	sql_getJnspJipPrevYearTb.append("				A.ORG_GRP_CD, ");
	sql_getJnspJipPrevYearTb.append("				A.ORG_GRP_NM , ");
	sql_getJnspJipPrevYearTb.append("				B.CODE_NM AS AREA, ");
	sql_getJnspJipPrevYearTb.append("				DATE_FORMAT(C.TRANSFER_DATE,'%Y년') AS DA, ");
	sql_getJnspJipPrevYearTb.append("			( ");
	sql_getJnspJipPrevYearTb.append("				SELECT COUNT(0) FROM TB_JIP_USE_STATUS AS B1 ");
	sql_getJnspJipPrevYearTb.append("				LEFT JOIN ");
	sql_getJnspJipPrevYearTb.append("						TB_SEARCH_PATENT_UTILITY_MODEL C1 ");
	sql_getJnspJipPrevYearTb.append("					ON	B1.REGIST_INFO = C1.APLC_NO ");
	sql_getJnspJipPrevYearTb.append("				LEFT JOIN ");
	sql_getJnspJipPrevYearTb.append("						TB_SEARCH_DESIGN D1 ");
	sql_getJnspJipPrevYearTb.append("					ON	B1.REGIST_INFO = D1.APLC_NO ");
	sql_getJnspJipPrevYearTb.append("				LEFT JOIN ");
	sql_getJnspJipPrevYearTb.append("						TB_SEARCH_BRAND E1 ");
	sql_getJnspJipPrevYearTb.append("					ON	B1.REGIST_INFO = E1.INTRL_APLC_NO ");
	sql_getJnspJipPrevYearTb.append("				LEFT JOIN ");
	sql_getJnspJipPrevYearTb.append("						TB_SEARCH_PROGRAM F1 ");
	sql_getJnspJipPrevYearTb.append("					ON	B1.REGIST_INFO = F1.REG_NO ");
	sql_getJnspJipPrevYearTb.append("				LEFT JOIN ");
	sql_getJnspJipPrevYearTb.append("						TB_SEARCH_KNOW_HOW G1 ");
	sql_getJnspJipPrevYearTb.append("					ON	B1.REGIST_INFO = G1.KNOW_HOW_NO ");
	sql_getJnspJipPrevYearTb.append("				WHERE B1.STATE = '2' ");
	sql_getJnspJipPrevYearTb.append("				AND A.ORG_GRP_CD = B1.ORG_GRP_CD ");
	sql_getJnspJipPrevYearTb.append("			) AS CNT ");
	sql_getJnspJipPrevYearTb.append("			FROM ");
	sql_getJnspJipPrevYearTb.append("			TB_ORG_GRP AS A ");
	sql_getJnspJipPrevYearTb.append("			LEFT JOIN TB_CODE AS B ");
	sql_getJnspJipPrevYearTb.append("			ON A.AREA_LOCATION_CD = B.CODE_CD ");
	sql_getJnspJipPrevYearTb.append("			LEFT JOIN TB_JIP_USE_STATUS AS C ");
	sql_getJnspJipPrevYearTb.append("			ON A.ORG_GRP_CD = C.ORG_GRP_CD ");
	sql_getJnspJipPrevYearTb.append("			WHERE (A.DELETE_YN != 'Y' OR A.DELETE_YN IS NULL) ");
	sql_getJnspJipPrevYearTb.append("			AND B.CODE_GRP_CD = 'AreaSigungu' ");
	sql_getJnspJipPrevYearTb.append("			AND A.APPLY_CD = '20' ");
	sql_getJnspJipPrevYearTb.append("			AND TO_DAYS(DATE_FORMAT(C.TRANSFER_DATE,'%Y-1-1')) <= TO_DAYS(NOW()) ");
	sql_getJnspJipPrevYearTb.append("			AND TO_DAYS(DATE_FORMAT(C.TRANSFER_DATE,'%Y-1-1')) >= TO_DAYS(NOW())-3650 ");
	sql_getJnspJipPrevYearTb.append("			GROUP BY DATE_FORMAT(C.TRANSFER_DATE,'%Y') ");
	sql_getJnspJipPrevYearTb.append("			ORDER BY DATE_FORMAT(C.TRANSFER_DATE,'%Y') DESC ");
	initializer.prepareQuery("sql_getJnspJipPrevYearTb", sql_getJnspJipPrevYearTb.toString());
}

private Logger logger = Logger.getLogger("com.activeintra");
class ReportHandler{
	//공통 변수 선언
	private Object[] userObj = null;
	private int nStartPage;		//각 쉬트별 시작 페이지 저장
	private int nMaxPage;		//한 쉬트가 실행된 후 생성된 최대 페이지 번호 저장
	private int nPageNum;		//현재 페이지 번호
	private int nYStartPos;		//쉬트에서 Y 시작 좌표
	private int nYEndPos;		//쉬트에서 Y 끝 좌표
	private int nYCurPos;		//현재 Y 좌표
	private int nYSavePos;		//연결된 멀티 프레임 쉬트에서 시작 Y 좌표 저장
	private int nYLastPos;		//연결된 멀티 프레임 쉬트에서 각 프레임의 마지막 Y 좌표 저장
	private int nXStartPos;		//쉬트에서 X 시작 좌표
	private int nXEndPos;		//쉬트에서 X 끝 좌표
	private int nXCurPos;		//현재 X 좌표
	private int nXSavePos;		//연결된 멀티 프레임 쉬트에서 시작 X 좌표 저장
	private int  nXLastPos;		//연결된 멀티 프레임 쉬트에서 각 프레임의 마지막 X 좌표 저장
	private boolean bIsBeforePageSkip;		//조건 밴드에서 페이지 넘기기 여부 판단
	private int nLoopRef;		//절대 양식에서 루프 참조 변수
	private int CELL_OBJECT = 0;
	private int DRAW_OBJECT = 1;
	private String isEmpty="";		//빈 문자열 비교에 사용
	private Map<String, String> mapParam;

	private int nBandRepeatType;	//1이면 반복밴드 가로 반복
	private int nBandWidth;		//반복밴드의 가로 폭
	private int nBandOffset;		//반복밴드 가로 반복 offset값
	private int nYBandStart;		//반복밴드 가로 반복 Y 시작 좌표
	private int nYBandEnd;		//반복밴드 가로 반복 Y 끝 좌표
	private int nHorRepeatNum;		//반복밴드 가로 반복 횟수
	private int nHorRepeatCnt;		//반복밴드 가로 반복 횟수 카운팅
	private Map<String, Integer> mapLeft;		//셀 Left
	private Map<String, Integer> mapTop;		//셀 Top
	private Map<String, Integer> mapWidth;		//셀 Width
	private Map<String, Integer> mapHeight;		//셀 Height
	private Map<String, String> mapStyle;		//셀 Style
	private HttpServletRequest request;
	private HttpServletResponse response;
	private PageContext pageContext;
	private JspWriter out;
	private HttpParameterDecoder decoder;

	private AIScriptManager manager;
	private String reportMode="AIScript";
	private String pdfFilename="";
	private String excelFilename="";

	//-----데이터 변수 선언-----
	long sheet10_A1 = 0L;
	String sheet10_A2 = "";
	String AI_CHART_OBJ41;
	String sheet10_B22 = "";
	String sheet10_N22 = "";
	String sheet10_B23 = "";
	long sheet10_N23 = 0L;
	String sheet10_B24 = "";

	//-----Connection, Statement, ResultSet 객체 선언-----
	private Connection conn_jnsp; 	 //jnsp Connection 객체
	private java.sql.PreparedStatement stat_getJnspJipPatentDate;		//ResultSet getJnspJipPatentDate 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipPatentDate;		//ResultSet getJnspJipPatentDate 객체
	private java.sql.PreparedStatement stat_getJnspJipPatentDateTt;		//ResultSet getJnspJipPatentDateTt 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipPatentDateTt;		//ResultSet getJnspJipPatentDateTt 객체
	private java.sql.PreparedStatement stat_getJnspJipPatentDateTb;		//ResultSet getJnspJipPatentDateTb 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipPatentDateTb;		//ResultSet getJnspJipPatentDateTb 객체
	private java.sql.PreparedStatement stat_getJnspJipPrevOrg;		//ResultSet getJnspJipPrevOrg 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipPrevOrg;		//ResultSet getJnspJipPrevOrg 객체
	private java.sql.PreparedStatement stat_getJnspJipPrevOrgTt;		//ResultSet getJnspJipPrevOrgTt 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipPrevOrgTt;		//ResultSet getJnspJipPrevOrgTt 객체
	private java.sql.PreparedStatement stat_getJnspJipPrevOrgTb;		//ResultSet getJnspJipPrevOrgTb 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipPrevOrgTb;		//ResultSet getJnspJipPrevOrgTb 객체
	private java.sql.PreparedStatement stat_getJnspJipPrevArea;		//ResultSet getJnspJipPrevArea 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipPrevArea;		//ResultSet getJnspJipPrevArea 객체
	private java.sql.PreparedStatement stat_getJnspJipPrevAreaTt;		//ResultSet getJnspJipPrevAreaTt 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipPrevAreaTt;		//ResultSet getJnspJipPrevAreaTt 객체
	private java.sql.PreparedStatement stat_getJnspJipPrevAreaTb;		//ResultSet getJnspJipPrevAreaTb 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipPrevAreaTb;		//ResultSet getJnspJipPrevAreaTb 객체
	private java.sql.PreparedStatement stat_getJnspJipPrevYear;		//ResultSet getJnspJipPrevYear 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipPrevYear;		//ResultSet getJnspJipPrevYear 객체
	private java.sql.PreparedStatement stat_getJnspJipPrevYearTt;		//ResultSet getJnspJipPrevYearTt 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipPrevYearTt;		//ResultSet getJnspJipPrevYearTt 객체
	private java.sql.PreparedStatement stat_getJnspJipPrevYearTb;		//ResultSet getJnspJipPrevYearTb 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipPrevYearTb;		//ResultSet getJnspJipPrevYearTb 객체

	//-----SQL 변수 선언-----
	private StringBuilder sql_getJnspJipPatentDate = new StringBuilder();		//ResultSet getJnspJipPatentDate 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_getJnspJipPatentDateTt = new StringBuilder();		//ResultSet getJnspJipPatentDateTt 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_getJnspJipPatentDateTb = new StringBuilder();		//ResultSet getJnspJipPatentDateTb 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_getJnspJipPrevOrg = new StringBuilder();		//ResultSet getJnspJipPrevOrg 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_getJnspJipPrevOrgTt = new StringBuilder();		//ResultSet getJnspJipPrevOrgTt 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_getJnspJipPrevOrgTb = new StringBuilder();		//ResultSet getJnspJipPrevOrgTb 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_getJnspJipPrevArea = new StringBuilder();		//ResultSet getJnspJipPrevArea 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_getJnspJipPrevAreaTt = new StringBuilder();		//ResultSet getJnspJipPrevAreaTt 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_getJnspJipPrevAreaTb = new StringBuilder();		//ResultSet getJnspJipPrevAreaTb 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_getJnspJipPrevYear = new StringBuilder();		//ResultSet getJnspJipPrevYear 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_getJnspJipPrevYearTt = new StringBuilder();		//ResultSet getJnspJipPrevYearTt 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_getJnspJipPrevYearTb = new StringBuilder();		//ResultSet getJnspJipPrevYearTb 객체를 생성하기 위한 쿼리문 저장

	//-----쿼리 필드 변수 선언-----
	//ResultSet getJnspJipPatentDate 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipPatentDate_IDX;
	private String getJnspJipPatentDate_ORG_NM;
	private String getJnspJipPatentDate_ORG_GRP_CD;
	private String getJnspJipPatentDate_AREA;
	private long getJnspJipPatentDate_CNT;

	//ResultSet getJnspJipPatentDateTt 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipPatentDateTt_IDX;
	private String getJnspJipPatentDateTt_ORG_NM;
	private String getJnspJipPatentDateTt_ORG_GRP_CD;
	private String getJnspJipPatentDateTt_AREA;
	private long getJnspJipPatentDateTt_CNT;

	//ResultSet getJnspJipPatentDateTb 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipPatentDateTb_IDX;
	private String getJnspJipPatentDateTb_ORG_NM;
	private String getJnspJipPatentDateTb_ORG_GRP_CD;
	private String getJnspJipPatentDateTb_AREA;
	private long getJnspJipPatentDateTb_CNT;

	//ResultSet getJnspJipPrevOrg 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipPrevOrg_ORG_GRP_CD;
	private String getJnspJipPrevOrg_AREA;
	private long getJnspJipPrevOrg_CNT;

	//ResultSet getJnspJipPrevOrgTt 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipPrevOrgTt_ORG_GRP_CD;
	private String getJnspJipPrevOrgTt_AREA;
	private long getJnspJipPrevOrgTt_CNT;

	//ResultSet getJnspJipPrevOrgTb 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipPrevOrgTb_ORG_GRP_CD;
	private String getJnspJipPrevOrgTb_AREA;
	private long getJnspJipPrevOrgTb_CNT;

	//ResultSet getJnspJipPrevArea 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipPrevArea_ORG_GRP_CD;
	private String getJnspJipPrevArea_ORG_GRP_NM;
	private String getJnspJipPrevArea_AREA;
	private long getJnspJipPrevArea_CNT;

	//ResultSet getJnspJipPrevAreaTt 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipPrevAreaTt_ORG_GRP_CD;
	private String getJnspJipPrevAreaTt_ORG_GRP_NM;
	private String getJnspJipPrevAreaTt_AREA;
	private long getJnspJipPrevAreaTt_CNT;

	//ResultSet getJnspJipPrevAreaTb 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipPrevAreaTb_ORG_GRP_CD;
	private String getJnspJipPrevAreaTb_ORG_GRP_NM;
	private String getJnspJipPrevAreaTb_AREA;
	private long getJnspJipPrevAreaTb_CNT;

	//ResultSet getJnspJipPrevYear 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipPrevYear_ORG_GRP_CD;
	private String getJnspJipPrevYear_ORG_GRP_NM;
	private String getJnspJipPrevYear_AREA;
	private String getJnspJipPrevYear_DA;
	private long getJnspJipPrevYear_CNT;

	//ResultSet getJnspJipPrevYearTt 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipPrevYearTt_ORG_GRP_CD;
	private String getJnspJipPrevYearTt_ORG_GRP_NM;
	private String getJnspJipPrevYearTt_AREA;
	private String getJnspJipPrevYearTt_DA;
	private long getJnspJipPrevYearTt_CNT;

	//ResultSet getJnspJipPrevYearTb 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipPrevYearTb_ORG_GRP_CD;
	private String getJnspJipPrevYearTb_ORG_GRP_NM;
	private String getJnspJipPrevYearTb_AREA;
	private String getJnspJipPrevYearTb_DA;
	private long getJnspJipPrevYearTb_CNT;

	//파라미터 변수 선언
	String userIdx_Param;
	String Idx_Param;

	//ReportHandler 생성자 함수
	ReportHandler(PageContext pageContext, HttpServletRequest request, HttpServletResponse response, Object[] userObj, HttpParameterDecoder decoder){
		this.pageContext = pageContext;
		this.request = request;
		this.response = response;
		this.userObj = userObj;
		this.decoder = decoder;
	}

	//ReportHandler 서비스 함수
	void service(JspWriter out) throws Exception{
		try{    //try 구문
			//변수 초기화
			this.out = out;
			nMaxPage = 0;   //nMaxPage 초기화

			nBandRepeatType=0;
			nBandWidth=0;
			nBandOffset=0;
			nYBandStart=0;
			nYBandEnd=0;
			nHorRepeatNum=0;
			nHorRepeatCnt=0;

			manager = new AIScriptManager(request, response, pageContext, out, logger, null);

			ServletContext context = pageContext.getServletContext();
			String temp = null;
			if(!context.getContextPath().equals("/"))
			temp = request.getRequestURI().replace(context.getContextPath(), "");
			else
			temp = request.getRequestURI();

			String path = temp.replace(".jsp", ".style");

			//셀 Rect, Style 값 저장
			setCellInfoMap();

			//파라미터 설정 함수 호출
			setParam();
			if(manager.open(reportMode, context.getRealPath(path)))
			{
				//스크립트 헤더 함수 호출
				getScriptHeader("A4", "2100x2970", "9", "VERTICAL", "56 70 56 70");

				//고정 데이터 초기화 함수 호출
				initConstVarient();

				//Connection 및 Statement 객체 생성 함수 호출
				createConnAndStateObject();

				//쿼리문 초기화 함수 호출
				initSQLConst();

				//쉬트 함수 호출
				//SHEET=Sheet1   FRAME=0 함수 호출
				executeSheet10();

				//---------------스크립트 종료---------------
				manager.scriptWrite("/AIReport", "", "", false);
				manager.close();
			}
		}catch(Exception e){    //catch 구문
			logger.error("---service function exception raised---");
			logger.error(e);
			throw e;
		}finally{    //finally 구문
			//DataSet Close
			cleanup(getJnspJipPrevYearTb, stat_getJnspJipPrevYearTb, null, null);
			cleanup(getJnspJipPrevYearTt, stat_getJnspJipPrevYearTt, null, null);
			cleanup(getJnspJipPrevYear, stat_getJnspJipPrevYear, null, null);
			cleanup(getJnspJipPrevAreaTb, stat_getJnspJipPrevAreaTb, null, null);
			cleanup(getJnspJipPrevAreaTt, stat_getJnspJipPrevAreaTt, null, null);
			cleanup(getJnspJipPrevArea, stat_getJnspJipPrevArea, null, null);
			cleanup(getJnspJipPrevOrgTb, stat_getJnspJipPrevOrgTb, null, null);
			cleanup(getJnspJipPrevOrgTt, stat_getJnspJipPrevOrgTt, null, null);
			cleanup(getJnspJipPrevOrg, stat_getJnspJipPrevOrg, null, null);
			cleanup(getJnspJipPatentDateTb, stat_getJnspJipPatentDateTb, null, null);
			cleanup(getJnspJipPatentDateTt, stat_getJnspJipPatentDateTt, null, null);
			cleanup(getJnspJipPatentDate, stat_getJnspJipPatentDate, null, null);
			cleanup(null, null, null, conn_jnsp);
		}    //end try
	}

	//-----쉬트 함수-----
	//-----SHEET=Sheet1   FRAME=Frame0 Start
	//-----폼 형식 : 상대 양식
	private void executeSheet10( ) throws Exception{
		//쉬트 초기화 함수 호출
		getSheetPaperInfo("User Define", "2700x2970", "256", "VERTICAL", "7 0 7 0");
		initSheetVariant(19, 12, 747, 831, true);

		//시작 페이지 번호 출력
		pageWrite(nPageNum);

		//밴드 함수 호출
		getScriptFromyyy(true, false);    //Void 밴드 호출
		getScriptFromview(true, true);    //Void 밴드 호출
		getScriptFromviewList(true, true);    //Void 밴드 호출
		getScriptFromTbList(true);    //반복 밴드 호출
		getScriptFromttttt(true, true);    //Void 밴드 호출

		//페이지 및 좌표 설정
		nMaxPage=(int)MAX((long)nMaxPage, (long)nPageNum);    //생성된 최대 페이지 번호 구하기
	}

	//-----밴드 함수-----
	//----yyy VoidBand Start----
	//----소속 쉬트 : SHEET=Sheet1    FRAME=Frame0
	//----밴드 이름 : yyy
	//----밴드 종류 : Void 밴드
	//----bIsFrist : 부모 밴드 함수나 쉬트 함수에서 최초로 호출될 때 true, 그 이후 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. true면 출력, false면 AI 스크립트를 생성하지 않음.
	//----nRepeatCnt : 부모 반복 밴드 수행 횟수와 연동 옵션 설정시 void 밴드가 수행할 반복 횟수 전달
	private void getScriptFromyyy(boolean bIsFirst, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=20;    //밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//DataSet 객체 생성
			//ResultSet getJnspJipPrevYearTt 객체의 생성
			if(getJnspJipPrevYearTt==null){
				getJnspJipPrevYearTt = stat_getJnspJipPrevYearTt.executeQuery();
			}else{
				getJnspJipPrevYearTt.beforeFirst();
			}

			//데이터 fetch
			if(getJnspJipPrevYearTt.next()){
				setFieldVariableFromgetJnspJipPrevYearTt();	//ResultSet getJnspJipPrevYearTt에서 필드 값 설정
			}else{
				setFieldInitFromgetJnspJipPrevYearTt();	//ResultSet getJnspJipPrevYearTt의 필드 값 초기화
			}

			//데이터 변수 초기화
			sheet10_A1=0L;

			//데이터 변수 할당
			sheet10_A1 = getJnspJipPrevYearTt_CNT;
		}    //end if(bIsFirst)

		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 영역 검사
			if(isPageSkip(nYCurPos+nBandHeight)){
				pageSkip(10);
			}

			//스크립트 출력 함수 호출
			writeScriptyyy();

			//다음 출력 좌표 설정
			nYCurPos=nYCurPos+nBandHeight;
		}   //end if(bIsPrint)
	}

	//----view VoidBand Start----
	//----소속 쉬트 : SHEET=Sheet1    FRAME=Frame0
	//----밴드 이름 : view
	//----밴드 종류 : Void 밴드
	//----bIsFrist : 부모 밴드 함수나 쉬트 함수에서 최초로 호출될 때 true, 그 이후 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. true면 출력, false면 AI 스크립트를 생성하지 않음.
	//----nRepeatCnt : 부모 반복 밴드 수행 횟수와 연동 옵션 설정시 void 밴드가 수행할 반복 횟수 전달
	private void getScriptFromview(boolean bIsFirst, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=419;    //밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//데이터 변수 초기화
			AI_CHART_OBJ41="";

			//데이터 변수 할당
			sheet10_A2="    지식재산 등록통계";
			getChartDataAI_CHART_OBJ41( );
		}    //end if(bIsFirst)

		if(getJnspJipPrevYearTt_CNT != 0 )
		{
		}
		else
		{
			return;
		}
		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 영역 검사
			if(isPageSkip(nYCurPos+nBandHeight)){
				pageSkip(10);
			}

			//스크립트 출력 함수 호출
			writeScriptview();

			//다음 출력 좌표 설정
			nYCurPos=nYCurPos+nBandHeight;
		}   //end if(bIsPrint)
	}

	//----viewList VoidBand Start----
	//----소속 쉬트 : SHEET=Sheet1    FRAME=Frame0
	//----밴드 이름 : viewList
	//----밴드 종류 : Void 밴드
	//----bIsFrist : 부모 밴드 함수나 쉬트 함수에서 최초로 호출될 때 true, 그 이후 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. true면 출력, false면 AI 스크립트를 생성하지 않음.
	//----nRepeatCnt : 부모 반복 밴드 수행 횟수와 연동 옵션 설정시 void 밴드가 수행할 반복 횟수 전달
	private void getScriptFromviewList(boolean bIsFirst, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=20;    //밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//데이터 변수 할당
			sheet10_B22="연 도";
			sheet10_N22="기술이전 건수";
		}    //end if(bIsFirst)

		if(getJnspJipPrevYearTt_CNT != 0 )
		{
		}
		else
		{
			return;
		}
		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 영역 검사
			if(isPageSkip(nYCurPos+nBandHeight)){
				pageSkip(10);
			}

			//스크립트 출력 함수 호출
			writeScriptviewList();

			//다음 출력 좌표 설정
			nYCurPos=nYCurPos+nBandHeight;
		}   //end if(bIsPrint)
	}

	//-----TbList RepeatBand Start-----
	//-----소속 쉬트 : SHEET=Sheet1   FRAME=Frame0
	//-----밴드 이름 : TbList
	//-----밴드 종류 : 반복 밴드
	//-----bIsPrint : 감추기 속성 설정 여부 true면 출력, false면 스크립트를 생성하지 않음
	private void getScriptFromTbList(boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=20;    //밴드 출력 높이
		boolean bIsFirst=true;

		//데이터 변수 초기화
		sheet10_B23="";
		sheet10_N23=0L;

		//DataSet 객체 생성
		//ResultSet getJnspJipPrevYearTb 객체의 생성
		if(getJnspJipPrevYearTb==null){
			getJnspJipPrevYearTb = stat_getJnspJipPrevYearTb.executeQuery();
		}else{
			getJnspJipPrevYearTb.beforeFirst();
		}

		if(getJnspJipPrevYearTt_CNT != 0 )
		{
		}
		else
		{
			return;
		}
		//--while Loop Start--##
		while(getJnspJipPrevYearTb.next()){   //자동으로 생성되는 반복 밴드의 루프문
			//데이터 fetch
			setFieldVariableFromgetJnspJipPrevYearTb();	//RecordSet getJnspJipPrevYearTb에서 필드 값 설정

			if(bIsFirst){   //밴드 호출 후 루프 내에서 한번 만 실행되는 코드
			}   //end if(bIsFirst)

			//데이터 변수 할당
			sheet10_B23 = getJnspJipPrevYearTb_DA;
			sheet10_N23 = getJnspJipPrevYearTb_CNT;

			//AI 스크립트 출력
			if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
				if(isPageSkip(nYCurPos+nBandHeight)){   //스크립트 출력 영역 검사
					//페이지 스킵 함수 호출
					pageSkip(10);
				}   //end if(page skip test)

				//스크립트 출력 함수 호출
				writeScriptTbList();

				//다음 출력 좌표 설정
				nYCurPos=nYCurPos+nBandHeight;
			}   //end if(bIsPrint)

			//bIsFirst 및 출력 라인 설정
			bIsFirst=false;
		}   //while end

		if(bIsFirst){   //while 루프가 실행되지 않은 경우
		} else {   //while 루프가 실행된 경우
		}   //루프 외부 end if(bIsFirst)
	}

	//----ttttt VoidBand Start----
	//----소속 쉬트 : SHEET=Sheet1    FRAME=Frame0
	//----밴드 이름 : ttttt
	//----밴드 종류 : Void 밴드
	//----bIsFrist : 부모 밴드 함수나 쉬트 함수에서 최초로 호출될 때 true, 그 이후 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. true면 출력, false면 AI 스크립트를 생성하지 않음.
	//----nRepeatCnt : 부모 반복 밴드 수행 횟수와 연동 옵션 설정시 void 밴드가 수행할 반복 횟수 전달
	private void getScriptFromttttt(boolean bIsFirst, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=20;    //밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//데이터 변수 할당
			sheet10_B24="데이터가 없습니다";
		}    //end if(bIsFirst)

		if(getJnspJipPrevYearTt_CNT == 0 )
		{
		}
		else
		{
			return;
		}
		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 영역 검사
			if(isPageSkip(nYCurPos+nBandHeight)){
				pageSkip(10);
			}

			//스크립트 출력 함수 호출
			writeScriptttttt();

			//다음 출력 좌표 설정
			nYCurPos=nYCurPos+nBandHeight;
		}   //end if(bIsPrint)
	}

	//-----스크립트 출력 함수-----
	//----yyy 스크립트 문 출력 함수----
	private void writeScriptyyy( ) throws Exception{
		//스크립트문 생성
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_A1"), nYCurPos+mapTop.get("sheet10_A1"), mapWidth.get("sheet10_A1"), mapHeight.get("sheet10_A1"), String.valueOf(sheet10_A1), "sheet10_A1", mapStyle.get("sheet10_A1"));
	}

	//----view 스크립트 문 출력 함수----
	private void writeScriptview( ) throws Exception{
		//스크립트문 생성
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_A2"), nYCurPos+mapTop.get("sheet10_A2"), mapWidth.get("sheet10_A2"), mapHeight.get("sheet10_A2"), sheet10_A2, "sheet10_A2", mapStyle.get("sheet10_A2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_J2"), nYCurPos+mapTop.get("sheet10_J2"), mapWidth.get("sheet10_J2"), mapHeight.get("sheet10_J2"), "", "sheet10_J2", mapStyle.get("sheet10_J2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_K2"), nYCurPos+mapTop.get("sheet10_K2"), mapWidth.get("sheet10_K2"), mapHeight.get("sheet10_K2"), "", "sheet10_K2", mapStyle.get("sheet10_K2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_L2"), nYCurPos+mapTop.get("sheet10_L2"), mapWidth.get("sheet10_L2"), mapHeight.get("sheet10_L2"), "", "sheet10_L2", mapStyle.get("sheet10_L2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_M2"), nYCurPos+mapTop.get("sheet10_M2"), mapWidth.get("sheet10_M2"), mapHeight.get("sheet10_M2"), "", "sheet10_M2", mapStyle.get("sheet10_M2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_N2"), nYCurPos+mapTop.get("sheet10_N2"), mapWidth.get("sheet10_N2"), mapHeight.get("sheet10_N2"), "", "sheet10_N2", mapStyle.get("sheet10_N2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_O2"), nYCurPos+mapTop.get("sheet10_O2"), mapWidth.get("sheet10_O2"), mapHeight.get("sheet10_O2"), "", "sheet10_O2", mapStyle.get("sheet10_O2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_P2"), nYCurPos+mapTop.get("sheet10_P2"), mapWidth.get("sheet10_P2"), mapHeight.get("sheet10_P2"), "", "sheet10_P2", mapStyle.get("sheet10_P2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_Q2"), nYCurPos+mapTop.get("sheet10_Q2"), mapWidth.get("sheet10_Q2"), mapHeight.get("sheet10_Q2"), "", "sheet10_Q2", mapStyle.get("sheet10_Q2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_R2"), nYCurPos+mapTop.get("sheet10_R2"), mapWidth.get("sheet10_R2"), mapHeight.get("sheet10_R2"), "", "sheet10_R2", mapStyle.get("sheet10_R2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_S2"), nYCurPos+mapTop.get("sheet10_S2"), mapWidth.get("sheet10_S2"), mapHeight.get("sheet10_S2"), "", "sheet10_S2", mapStyle.get("sheet10_S2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_T2"), nYCurPos+mapTop.get("sheet10_T2"), mapWidth.get("sheet10_T2"), mapHeight.get("sheet10_T2"), "", "sheet10_T2", mapStyle.get("sheet10_T2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_U2"), nYCurPos+mapTop.get("sheet10_U2"), mapWidth.get("sheet10_U2"), mapHeight.get("sheet10_U2"), "", "sheet10_U2", mapStyle.get("sheet10_U2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_V2"), nYCurPos+mapTop.get("sheet10_V2"), mapWidth.get("sheet10_V2"), mapHeight.get("sheet10_V2"), "", "sheet10_V2", mapStyle.get("sheet10_V2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_W2"), nYCurPos+mapTop.get("sheet10_W2"), mapWidth.get("sheet10_W2"), mapHeight.get("sheet10_W2"), "", "sheet10_W2", mapStyle.get("sheet10_W2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_X2"), nYCurPos+mapTop.get("sheet10_X2"), mapWidth.get("sheet10_X2"), mapHeight.get("sheet10_X2"), "", "sheet10_X2", mapStyle.get("sheet10_X2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_Y2"), nYCurPos+mapTop.get("sheet10_Y2"), mapWidth.get("sheet10_Y2"), mapHeight.get("sheet10_Y2"), "", "sheet10_Y2", mapStyle.get("sheet10_Y2"));
		objectWrite(DRAW_OBJECT, nXCurPos, nYCurPos+33, 726, 362, AI_CHART_OBJ41, "AI_CHART_OBJ41", "draw_style_0");
	}

	//----viewList 스크립트 문 출력 함수----
	private void writeScriptviewList( ) throws Exception{
		//스크립트문 생성
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_B22"), nYCurPos+mapTop.get("sheet10_B22"), mapWidth.get("sheet10_B22"), mapHeight.get("sheet10_B22"), sheet10_B22, "sheet10_B22", mapStyle.get("sheet10_B22"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_N22"), nYCurPos+mapTop.get("sheet10_N22"), mapWidth.get("sheet10_N22"), mapHeight.get("sheet10_N22"), sheet10_N22, "sheet10_N22", mapStyle.get("sheet10_N22"));
	}

	//----TbList 스크립트 문 출력 함수----
	private void writeScriptTbList(  ) throws Exception{
		//스크립트문 생성
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_B23"), nYCurPos+mapTop.get("sheet10_B23"), mapWidth.get("sheet10_B23"), mapHeight.get("sheet10_B23"), sheet10_B23, "sheet10_B23", mapStyle.get("sheet10_B23"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_N23"), nYCurPos+mapTop.get("sheet10_N23"), mapWidth.get("sheet10_N23"), mapHeight.get("sheet10_N23"), String.valueOf(sheet10_N23), "sheet10_N23", mapStyle.get("sheet10_N23"));
	}

	//----ttttt 스크립트 문 출력 함수----
	private void writeScriptttttt( ) throws Exception{
		//스크립트문 생성
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_B24"), nYCurPos+mapTop.get("sheet10_B24"), mapWidth.get("sheet10_B24"), mapHeight.get("sheet10_B24"), sheet10_B24, "sheet10_B24", mapStyle.get("sheet10_B24"));
	}

	private void getBgImageScriptEx(int nIndex) throws Exception{
	}

	//-----Connection 및 Statement 객체 생성 함수-----
	private void createConnAndStateObject() throws Exception{
		//jnsp Connection 객체 생성
		Class.forName("com.mysql.jdbc.Driver");
		conn_jnsp = DriverManager.getConnection("jdbc:mysql://jnsp.re.kr:3306/jnspcms??useUnicode=true&characterEncoding=utf-8", "jnspcms", "jnspcms!@12");
	}

	//-----ResultSet, PreparedStatement, Connection, CallableStatement Close 함수-----
	private void cleanup(Object rs, PreparedStatement st, CallableStatement cs, Connection conn){
		if(rs != null){
			try{
				if(rs instanceof ResultSet){
					((ResultSet)rs).close();
				}else if(rs instanceof com.activeintra.util.uds.AIDataSource){
					((com.activeintra.util.uds.AIDataSource)rs).close();
				}else if(rs instanceof com.activeintra.util.uds.XMLSetHandler){
					((com.activeintra.util.uds.XMLSetHandler)rs).close();
				}else if(rs instanceof com.activeintra.util.uds.CSVSetHandler){
					((com.activeintra.util.uds.CSVSetHandler)rs).close();
				}else if(rs instanceof com.activeintra.util.uds.JSONSetHandler){
					((com.activeintra.util.uds.JSONSetHandler)rs).close();
				}
			}
			catch(SQLException e){
				logger.error(e);
			}
		}

		if(st != null){
			try{
				st.close();
			}
			catch(SQLException e){
				logger.error(e);
			}
		}

		if(cs != null){
			try{
				cs.close();
			}
			catch(SQLException e){
				logger.error(e);
			}
		}

		if(conn != null){
			try{
				conn.close();
			}
			catch(SQLException e){
				logger.error(e);
			}
		}
	}

	//-----SQL문 변수 초기화 함수-----
	private void initSQLConst() throws Exception {
		stat_getJnspJipPatentDate = initializer.configPreparedStatement("sql_getJnspJipPatentDate", mapParam, conn_jnsp, null);

		stat_getJnspJipPatentDateTt = initializer.configPreparedStatement("sql_getJnspJipPatentDateTt", mapParam, conn_jnsp, null);

		stat_getJnspJipPatentDateTb = initializer.configPreparedStatement("sql_getJnspJipPatentDateTb", mapParam, conn_jnsp, null);

		stat_getJnspJipPrevOrg = initializer.configPreparedStatement("sql_getJnspJipPrevOrg", mapParam, conn_jnsp, null);

		stat_getJnspJipPrevOrgTt = initializer.configPreparedStatement("sql_getJnspJipPrevOrgTt", mapParam, conn_jnsp, null);

		stat_getJnspJipPrevOrgTb = initializer.configPreparedStatement("sql_getJnspJipPrevOrgTb", mapParam, conn_jnsp, null);

		stat_getJnspJipPrevArea = initializer.configPreparedStatement("sql_getJnspJipPrevArea", mapParam, conn_jnsp, null);

		stat_getJnspJipPrevAreaTt = initializer.configPreparedStatement("sql_getJnspJipPrevAreaTt", mapParam, conn_jnsp, null);

		stat_getJnspJipPrevAreaTb = initializer.configPreparedStatement("sql_getJnspJipPrevAreaTb", mapParam, conn_jnsp, null);

		stat_getJnspJipPrevYear = initializer.configPreparedStatement("sql_getJnspJipPrevYear", mapParam, conn_jnsp, null);

		stat_getJnspJipPrevYearTt = initializer.configPreparedStatement("sql_getJnspJipPrevYearTt", mapParam, conn_jnsp, null);

		stat_getJnspJipPrevYearTb = initializer.configPreparedStatement("sql_getJnspJipPrevYearTb", mapParam, conn_jnsp, null);
	}

	//-----ResultSet 객체에서 필드 값 설정 함수-----
	//ResultSet getJnspJipPatentDate 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipPatentDate() throws Exception{
		getJnspJipPatentDate_IDX = GetB(getJnspJipPatentDate.getString(1));
		getJnspJipPatentDate_ORG_NM = GetB(getJnspJipPatentDate.getString(2));
		getJnspJipPatentDate_ORG_GRP_CD = GetB(getJnspJipPatentDate.getString(3));
		getJnspJipPatentDate_AREA = GetB(getJnspJipPatentDate.getString(4));
		getJnspJipPatentDate_CNT = getJnspJipPatentDate.getLong(5);
	}

	//ResultSet getJnspJipPatentDate 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipPatentDate(){
		getJnspJipPatentDate_IDX = "";
		getJnspJipPatentDate_ORG_NM = "";
		getJnspJipPatentDate_ORG_GRP_CD = "";
		getJnspJipPatentDate_AREA = "";
		getJnspJipPatentDate_CNT = 0L;
	}

	//ResultSet getJnspJipPatentDate 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipPatentDate() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipPatentDate.getObject(1));
		row.add(getJnspJipPatentDate.getObject(2));
		row.add(getJnspJipPatentDate.getObject(3));
		row.add(getJnspJipPatentDate.getObject(4));
		row.add(getJnspJipPatentDate.getLong(5));

		return row;
	}

	//ResultSet getJnspJipPatentDateTt 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipPatentDateTt() throws Exception{
		getJnspJipPatentDateTt_IDX = GetB(getJnspJipPatentDateTt.getString(1));
		getJnspJipPatentDateTt_ORG_NM = GetB(getJnspJipPatentDateTt.getString(2));
		getJnspJipPatentDateTt_ORG_GRP_CD = GetB(getJnspJipPatentDateTt.getString(3));
		getJnspJipPatentDateTt_AREA = GetB(getJnspJipPatentDateTt.getString(4));
		getJnspJipPatentDateTt_CNT = getJnspJipPatentDateTt.getLong(5);
	}

	//ResultSet getJnspJipPatentDateTt 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipPatentDateTt(){
		getJnspJipPatentDateTt_IDX = "";
		getJnspJipPatentDateTt_ORG_NM = "";
		getJnspJipPatentDateTt_ORG_GRP_CD = "";
		getJnspJipPatentDateTt_AREA = "";
		getJnspJipPatentDateTt_CNT = 0L;
	}

	//ResultSet getJnspJipPatentDateTt 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipPatentDateTt() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipPatentDateTt.getObject(1));
		row.add(getJnspJipPatentDateTt.getObject(2));
		row.add(getJnspJipPatentDateTt.getObject(3));
		row.add(getJnspJipPatentDateTt.getObject(4));
		row.add(getJnspJipPatentDateTt.getLong(5));

		return row;
	}

	//ResultSet getJnspJipPatentDateTb 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipPatentDateTb() throws Exception{
		getJnspJipPatentDateTb_IDX = GetB(getJnspJipPatentDateTb.getString(1));
		getJnspJipPatentDateTb_ORG_NM = GetB(getJnspJipPatentDateTb.getString(2));
		getJnspJipPatentDateTb_ORG_GRP_CD = GetB(getJnspJipPatentDateTb.getString(3));
		getJnspJipPatentDateTb_AREA = GetB(getJnspJipPatentDateTb.getString(4));
		getJnspJipPatentDateTb_CNT = getJnspJipPatentDateTb.getLong(5);
	}

	//ResultSet getJnspJipPatentDateTb 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipPatentDateTb(){
		getJnspJipPatentDateTb_IDX = "";
		getJnspJipPatentDateTb_ORG_NM = "";
		getJnspJipPatentDateTb_ORG_GRP_CD = "";
		getJnspJipPatentDateTb_AREA = "";
		getJnspJipPatentDateTb_CNT = 0L;
	}

	//ResultSet getJnspJipPatentDateTb 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipPatentDateTb() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipPatentDateTb.getObject(1));
		row.add(getJnspJipPatentDateTb.getObject(2));
		row.add(getJnspJipPatentDateTb.getObject(3));
		row.add(getJnspJipPatentDateTb.getObject(4));
		row.add(getJnspJipPatentDateTb.getLong(5));

		return row;
	}

	//ResultSet getJnspJipPrevOrg 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipPrevOrg() throws Exception{
		getJnspJipPrevOrg_ORG_GRP_CD = GetB(getJnspJipPrevOrg.getString(1));
		getJnspJipPrevOrg_AREA = GetB(getJnspJipPrevOrg.getString(2));
		getJnspJipPrevOrg_CNT = getJnspJipPrevOrg.getLong(3);
	}

	//ResultSet getJnspJipPrevOrg 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipPrevOrg(){
		getJnspJipPrevOrg_ORG_GRP_CD = "";
		getJnspJipPrevOrg_AREA = "";
		getJnspJipPrevOrg_CNT = 0L;
	}

	//ResultSet getJnspJipPrevOrg 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipPrevOrg() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipPrevOrg.getObject(1));
		row.add(getJnspJipPrevOrg.getObject(2));
		row.add(getJnspJipPrevOrg.getLong(3));

		return row;
	}

	//ResultSet getJnspJipPrevOrgTt 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipPrevOrgTt() throws Exception{
		getJnspJipPrevOrgTt_ORG_GRP_CD = GetB(getJnspJipPrevOrgTt.getString(1));
		getJnspJipPrevOrgTt_AREA = GetB(getJnspJipPrevOrgTt.getString(2));
		getJnspJipPrevOrgTt_CNT = getJnspJipPrevOrgTt.getLong(3);
	}

	//ResultSet getJnspJipPrevOrgTt 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipPrevOrgTt(){
		getJnspJipPrevOrgTt_ORG_GRP_CD = "";
		getJnspJipPrevOrgTt_AREA = "";
		getJnspJipPrevOrgTt_CNT = 0L;
	}

	//ResultSet getJnspJipPrevOrgTt 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipPrevOrgTt() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipPrevOrgTt.getObject(1));
		row.add(getJnspJipPrevOrgTt.getObject(2));
		row.add(getJnspJipPrevOrgTt.getLong(3));

		return row;
	}

	//ResultSet getJnspJipPrevOrgTb 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipPrevOrgTb() throws Exception{
		getJnspJipPrevOrgTb_ORG_GRP_CD = GetB(getJnspJipPrevOrgTb.getString(1));
		getJnspJipPrevOrgTb_AREA = GetB(getJnspJipPrevOrgTb.getString(2));
		getJnspJipPrevOrgTb_CNT = getJnspJipPrevOrgTb.getLong(3);
	}

	//ResultSet getJnspJipPrevOrgTb 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipPrevOrgTb(){
		getJnspJipPrevOrgTb_ORG_GRP_CD = "";
		getJnspJipPrevOrgTb_AREA = "";
		getJnspJipPrevOrgTb_CNT = 0L;
	}

	//ResultSet getJnspJipPrevOrgTb 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipPrevOrgTb() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipPrevOrgTb.getObject(1));
		row.add(getJnspJipPrevOrgTb.getObject(2));
		row.add(getJnspJipPrevOrgTb.getLong(3));

		return row;
	}

	//ResultSet getJnspJipPrevArea 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipPrevArea() throws Exception{
		getJnspJipPrevArea_ORG_GRP_CD = GetB(getJnspJipPrevArea.getString(1));
		getJnspJipPrevArea_ORG_GRP_NM = GetB(getJnspJipPrevArea.getString(2));
		getJnspJipPrevArea_AREA = GetB(getJnspJipPrevArea.getString(3));
		getJnspJipPrevArea_CNT = getJnspJipPrevArea.getLong(4);
	}

	//ResultSet getJnspJipPrevArea 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipPrevArea(){
		getJnspJipPrevArea_ORG_GRP_CD = "";
		getJnspJipPrevArea_ORG_GRP_NM = "";
		getJnspJipPrevArea_AREA = "";
		getJnspJipPrevArea_CNT = 0L;
	}

	//ResultSet getJnspJipPrevArea 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipPrevArea() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipPrevArea.getObject(1));
		row.add(getJnspJipPrevArea.getObject(2));
		row.add(getJnspJipPrevArea.getObject(3));
		row.add(getJnspJipPrevArea.getLong(4));

		return row;
	}

	//ResultSet getJnspJipPrevAreaTt 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipPrevAreaTt() throws Exception{
		getJnspJipPrevAreaTt_ORG_GRP_CD = GetB(getJnspJipPrevAreaTt.getString(1));
		getJnspJipPrevAreaTt_ORG_GRP_NM = GetB(getJnspJipPrevAreaTt.getString(2));
		getJnspJipPrevAreaTt_AREA = GetB(getJnspJipPrevAreaTt.getString(3));
		getJnspJipPrevAreaTt_CNT = getJnspJipPrevAreaTt.getLong(4);
	}

	//ResultSet getJnspJipPrevAreaTt 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipPrevAreaTt(){
		getJnspJipPrevAreaTt_ORG_GRP_CD = "";
		getJnspJipPrevAreaTt_ORG_GRP_NM = "";
		getJnspJipPrevAreaTt_AREA = "";
		getJnspJipPrevAreaTt_CNT = 0L;
	}

	//ResultSet getJnspJipPrevAreaTt 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipPrevAreaTt() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipPrevAreaTt.getObject(1));
		row.add(getJnspJipPrevAreaTt.getObject(2));
		row.add(getJnspJipPrevAreaTt.getObject(3));
		row.add(getJnspJipPrevAreaTt.getLong(4));

		return row;
	}

	//ResultSet getJnspJipPrevAreaTb 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipPrevAreaTb() throws Exception{
		getJnspJipPrevAreaTb_ORG_GRP_CD = GetB(getJnspJipPrevAreaTb.getString(1));
		getJnspJipPrevAreaTb_ORG_GRP_NM = GetB(getJnspJipPrevAreaTb.getString(2));
		getJnspJipPrevAreaTb_AREA = GetB(getJnspJipPrevAreaTb.getString(3));
		getJnspJipPrevAreaTb_CNT = getJnspJipPrevAreaTb.getLong(4);
	}

	//ResultSet getJnspJipPrevAreaTb 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipPrevAreaTb(){
		getJnspJipPrevAreaTb_ORG_GRP_CD = "";
		getJnspJipPrevAreaTb_ORG_GRP_NM = "";
		getJnspJipPrevAreaTb_AREA = "";
		getJnspJipPrevAreaTb_CNT = 0L;
	}

	//ResultSet getJnspJipPrevAreaTb 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipPrevAreaTb() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipPrevAreaTb.getObject(1));
		row.add(getJnspJipPrevAreaTb.getObject(2));
		row.add(getJnspJipPrevAreaTb.getObject(3));
		row.add(getJnspJipPrevAreaTb.getLong(4));

		return row;
	}

	//ResultSet getJnspJipPrevYear 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipPrevYear() throws Exception{
		getJnspJipPrevYear_ORG_GRP_CD = GetB(getJnspJipPrevYear.getString(1));
		getJnspJipPrevYear_ORG_GRP_NM = GetB(getJnspJipPrevYear.getString(2));
		getJnspJipPrevYear_AREA = GetB(getJnspJipPrevYear.getString(3));
		getJnspJipPrevYear_DA = GetB(getJnspJipPrevYear.getString(4));
		getJnspJipPrevYear_CNT = getJnspJipPrevYear.getLong(5);
	}

	//ResultSet getJnspJipPrevYear 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipPrevYear(){
		getJnspJipPrevYear_ORG_GRP_CD = "";
		getJnspJipPrevYear_ORG_GRP_NM = "";
		getJnspJipPrevYear_AREA = "";
		getJnspJipPrevYear_DA = "";
		getJnspJipPrevYear_CNT = 0L;
	}

	//ResultSet getJnspJipPrevYear 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipPrevYear() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipPrevYear.getObject(1));
		row.add(getJnspJipPrevYear.getObject(2));
		row.add(getJnspJipPrevYear.getObject(3));
		row.add(getJnspJipPrevYear.getObject(4));
		row.add(getJnspJipPrevYear.getLong(5));

		return row;
	}

	//ResultSet getJnspJipPrevYearTt 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipPrevYearTt() throws Exception{
		getJnspJipPrevYearTt_ORG_GRP_CD = GetB(getJnspJipPrevYearTt.getString(1));
		getJnspJipPrevYearTt_ORG_GRP_NM = GetB(getJnspJipPrevYearTt.getString(2));
		getJnspJipPrevYearTt_AREA = GetB(getJnspJipPrevYearTt.getString(3));
		getJnspJipPrevYearTt_DA = GetB(getJnspJipPrevYearTt.getString(4));
		getJnspJipPrevYearTt_CNT = getJnspJipPrevYearTt.getLong(5);
	}

	//ResultSet getJnspJipPrevYearTt 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipPrevYearTt(){
		getJnspJipPrevYearTt_ORG_GRP_CD = "";
		getJnspJipPrevYearTt_ORG_GRP_NM = "";
		getJnspJipPrevYearTt_AREA = "";
		getJnspJipPrevYearTt_DA = "";
		getJnspJipPrevYearTt_CNT = 0L;
	}

	//ResultSet getJnspJipPrevYearTt 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipPrevYearTt() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipPrevYearTt.getObject(1));
		row.add(getJnspJipPrevYearTt.getObject(2));
		row.add(getJnspJipPrevYearTt.getObject(3));
		row.add(getJnspJipPrevYearTt.getObject(4));
		row.add(getJnspJipPrevYearTt.getLong(5));

		return row;
	}

	//ResultSet getJnspJipPrevYearTb 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipPrevYearTb() throws Exception{
		getJnspJipPrevYearTb_ORG_GRP_CD = GetB(getJnspJipPrevYearTb.getString(1));
		getJnspJipPrevYearTb_ORG_GRP_NM = GetB(getJnspJipPrevYearTb.getString(2));
		getJnspJipPrevYearTb_AREA = GetB(getJnspJipPrevYearTb.getString(3));
		getJnspJipPrevYearTb_DA = GetB(getJnspJipPrevYearTb.getString(4));
		getJnspJipPrevYearTb_CNT = getJnspJipPrevYearTb.getLong(5);
	}

	//ResultSet getJnspJipPrevYearTb 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipPrevYearTb(){
		getJnspJipPrevYearTb_ORG_GRP_CD = "";
		getJnspJipPrevYearTb_ORG_GRP_NM = "";
		getJnspJipPrevYearTb_AREA = "";
		getJnspJipPrevYearTb_DA = "";
		getJnspJipPrevYearTb_CNT = 0L;
	}

	//ResultSet getJnspJipPrevYearTb 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipPrevYearTb() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipPrevYearTb.getObject(1));
		row.add(getJnspJipPrevYearTb.getObject(2));
		row.add(getJnspJipPrevYearTb.getObject(3));
		row.add(getJnspJipPrevYearTb.getObject(4));
		row.add(getJnspJipPrevYearTb.getLong(5));

		return row;
	}

	//-----고정 데이터 초기화 함수-----
	private void initConstVarientEx(){
	}

	//----AI_CHART_OBJ41 챠트 데이터 함수----
	private void getChartDataAI_CHART_OBJ41( ) throws Exception{
		//DataSet 객체 생성
		//ResultSet getJnspJipPrevYear 객체의 생성
		if(getJnspJipPrevYear==null){
			getJnspJipPrevYear = stat_getJnspJipPrevYear.executeQuery();
		}else{
			getJnspJipPrevYear.beforeFirst();
		}
		if(!getJnspJipPrevYear.isBeforeFirst()){		//생성된 ResultSet에 레코드가 없으면
			return;
		}

		//계열(Series) 필드 설정
		AI_CHART_OBJ41="\t";
		AI_CHART_OBJ41=AI_CHART_OBJ41 + "CNT\r\n";

		while(getJnspJipPrevYear.next()){   //데이터 루프문
			//데이터 fetch
			setFieldVariableFromgetJnspJipPrevYear();   //RecordSet getJnspJipPrevYear에서 필드 값 설정

			//X축 레이블 필드 설정
			AI_CHART_OBJ41=AI_CHART_OBJ41 + getJnspJipPrevYear_DA + "\t";

			//데이터 설정
			AI_CHART_OBJ41=AI_CHART_OBJ41 + getJnspJipPrevYear_CNT + "\r\n";
		}   //while end
	}

	//-----공통 함수 선언-----
	//파라미터 설정 함수
	private void setParam() {
		//SetParam_AutoCode
		reportMode=decoder.getParameterB("reportMode");
		if(reportMode.equals("")) {
			reportMode="HTML";
		}
		manager.setParam("pdfFilename:" + pdfFilename + "," + "excelFilename:" + excelFilename + "," + decoder.getParameterB("reportParams"));

		//char data[] = {0x14};
		//String str = new String(data);
		mapParam = new HashMap<String, String>();

		userIdx_Param=decoder.getParameterB("userIdx");
		//userIdx_Param=aiReplace(userIdx_Param, str, "\n");
		mapParam.put("userIdx", userIdx_Param);

		Idx_Param=decoder.getParameterB("Idx");
		//Idx_Param=aiReplace(Idx_Param, str, "\n");
		mapParam.put("Idx", Idx_Param);
	}

	//상수 데이터 초기화 래퍼 함수
	private void initConstVarient() {
		//InitConstVarient_AutoCode
		initConstVarientEx();
	}

	//배경 이미지 출력 래퍼 함수
	private void getBgImageScript(int nIndex) throws Exception{
		//GetBgImageScript_AutoCode
		getBgImageScriptEx(nIndex);
	}

	//페이지 스킵 함수
	//페이지 스킵시 호출되는 함수로서 페이지 번호를 증가시키고 페이지 지시문 출력 그리고 Y좌표 초기화
	//매개변수에 따라 해당 쉬트의 배경 이미지, 머리글 밴드, 바닥글 밴드 함수 호출
	private void pageSkip(int nIndex) throws Exception{
		//PageSkip_AutoCode
		if(nBandRepeatType==1) {
			int tmpX;
			tmpX=nXCurPos+nBandWidth+nBandOffset;
			nHorRepeatCnt=nHorRepeatCnt+1;
			if(tmpX+nBandWidth>nXEndPos || nHorRepeatCnt==nHorRepeatNum) {
				nYBandStart=nYStartPos;
				nYBandEnd=0;
				nHorRepeatCnt=0;
			}else{
				if(nYBandEnd<nYCurPos) {
					nYBandEnd=nYCurPos;
				}
				nYCurPos=nYBandStart;
				nXCurPos=tmpX;
				return;
			}
		}

		nXCurPos=nXStartPos;
		nYCurPos=nYStartPos;
		nPageNum=nPageNum+1;
		pageWrite(nPageNum);

		switch(nIndex){
			case 10:		//SHEET=Sheet=1   FRAME=0에서 페이지 스킵시
			break;
		}
	}

	//페이지 스킵이 필요한지 검사하는 함수
	private boolean isPageSkip(int nTestPos){
		//IsPageSkip_AutoCode
		if(nTestPos>nYEndPos){
			return true;
		}else{
			return false;
		}
	}

	//문자의 폭을 조사하여 데이터의 출력 높이를 자동적으로 조정하는 함수
	private int getPrintHeight(String data, int[] charWidth, int fontSize, int printWidth, int printHeight, int nMaxHeight, int horMargin, int vertMargin, String styleName) throws Exception {
		//GetPrintHeight_AutoCode
		if(data.equals(isEmpty)){
			return nMaxHeight;
		}
		if(!reportMode.equals("AIScript")) {
			printWidth+=horMargin;
			printHeight+=vertMargin;
			int needHeight=(int)TextHandler.wordWrapTextEx(printWidth, data, styleName, manager.getAIStyleInfo());

			if(needHeight>printHeight) {
				needHeight=needHeight-printHeight;
			}else{
				needHeight=0;
			}

			needHeight=(int)MAX((long)needHeight,(long)nMaxHeight);
			return needHeight;
		}
		else {
			int ch;
			int len = 95;
			int []width = new int[1];
			width[0] = 0;
			int asciiWidth = 0;
			int linePitch = (int)(fontSize*1.4);
			int height = linePitch;
			int size = data.length();
			int ascIndex=0;
			printWidth = printWidth*100;

			for (int i = 0; i < size; i++) {
				ch = data.charAt(i);

				if(ch<32 && !(ch==10 || ch==20 || ch==13)){
					continue;
				}

				if((ch>64 && ch<91) || (ch>96 && ch<123)) {
					if(asciiWidth==0){
						ascIndex=i;
					}

					asciiWidth += charWidth[ch-32];
					if (i==size-1){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i+1, linePitch, printWidth, width, asciiWidth);
					}
				} else if (ch==10 || ch==20 || ch==13) {
					if(asciiWidth>0){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i, linePitch, printWidth, width, asciiWidth);
						asciiWidth = 0;
					}

					width[0] = 0;
					height += linePitch;

					if (ch==13) {
						if ((i != size-1) && (10 == (int)data.charAt(i+1))) {
							i++;
						}
					}
				} else {
					if(asciiWidth>0){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i, linePitch, printWidth, width, asciiWidth);
						asciiWidth=0;
					}

					if(ch>=32 && ch<=127){
						width[0] += charWidth[ch-32];
						if (width[0] > printWidth) {
							if (ch==32)
							{
								width[0] = 0;
							}
							else
							{
								width[0] = charWidth[ch-32];
							}
							height += linePitch;
						}
					}else{
						width[0] += charWidth[len];
						if (width[0] > printWidth) {
							width[0] = charWidth[len];
							height += linePitch;
						}
					}
				}
			}

			if (height>printHeight) {
				height=height-printHeight;
			}else{
				height=0;
			}

			height = (int)MAX((long)height,(long)nMaxHeight);
			return height;
		}
	}

	//영문 단어의 폭을 문자별로 조사하여 데이터의 출력 높이를 조정하는 함수
	private int getWordWrapHeight(String data, int[] charWidth, int nStartIndex, int nEndIndex, int linePitch, int printWidth, int []width, int asciiWidth){
		//GetWordWrapHeight_AutoCode
		int ch;
		int height=0;

		if(asciiWidth>printWidth){
			for(int i=nStartIndex; i<nEndIndex; i++){
				ch=data.charAt(i);
				width[0]+=charWidth[ch-32];
				if(width[0]>printWidth){
					width[0]=charWidth[ch-32];
					height+=linePitch;
				}
			}
		}else{
			width[0]+=asciiWidth;
			if(width[0]>printWidth){
				width[0]=asciiWidth;
				height+=linePitch;
			}
		}

		return height;
	}

	//문자의 폭을 조사하여 데이터의 출력 높이를 자동적으로 조정하고 페이지 초과시 초과하는 데이터 절삭하는 함수
	private int getPrintHeightEx(String data, String[] strSplitData, int[] charWidth, int fontSize, int printWidth, int nExtHeight, int nMaxHeight, int horMargin, int vertMargin, String styleName) throws Exception {
		//GetPrintHeightEx_AutoCode
		if(!reportMode.equals("AIScript")) {
			strSplitData[0]="";
			strSplitData[1]="";
			printWidth+=horMargin;
			nExtHeight+=vertMargin;
			int needHeight=(int)TextHandler.wordWrapTextEx(printWidth, nExtHeight, data, strSplitData, styleName, manager.getAIStyleInfo());

			if(needHeight>nExtHeight) {
				needHeight=nExtHeight;
			}

			needHeight = (int)MAX((long)needHeight,(long)nMaxHeight);
			return needHeight;
		}
		else {
			int ch;
			int i;
			int len = 95;
			int []width = new int[1];
			width[0] = 0;
			int asciiWidth = 0;
			int linePitch = (int)(fontSize*1.4);
			int height = linePitch;
			int size = data.length();
			int ascIndex=0;
			boolean bSplit=false;
			strSplitData[0]="";
			strSplitData[1]="";
			printWidth = printWidth*100;

			for (i = 0; i < size; i++) {
				ch = data.charAt(i);

				if(ch<32 && !(ch==10 || ch==20 || ch==13)){
					continue;
				}

				if ((ch>64 && ch<91) || (ch>96 && ch<123)) {
					if(asciiWidth==0){
						ascIndex=i;
					}

					asciiWidth += charWidth[ch-32];
					if (i==size-1){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i+1, linePitch, printWidth, width, asciiWidth);
						if(height>nExtHeight){
							height=nExtHeight;
							bSplit=true;
							i=ascIndex;
							break;
						}
					}
				}else if (ch==10 || ch==20 || ch==13) {
					if(asciiWidth>0){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i, linePitch, printWidth, width, asciiWidth);
						if(height>nExtHeight){
							height=nExtHeight;
							bSplit=true;
							i=ascIndex;
							break;
						}
						asciiWidth = 0;
					}

					width[0] = 0;
					height += linePitch;
					if (ch==13){
						if ((i != size-1) && (10 == (int)data.charAt(i+1))) {
							i++;
						}
					}

					if(height>nExtHeight){
						height=nExtHeight;
						if(i!=size-1){
							bSplit=true;
							i++;
						}
						break;
					}
				}else{
					if(asciiWidth>0){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i, linePitch, printWidth, width, asciiWidth);
						if(height>nExtHeight){
							height=nExtHeight;
							bSplit=true;
							i=ascIndex;
							break;
						}
						asciiWidth=0;
					}

					if(ch>=32 && ch<=127){
						width[0] += charWidth[ch-32];
						if (width[0] > printWidth) {
							if (ch==32)
							{
								width[0] = 0;
							}
							else
							{
								width[0] = charWidth[ch-32];
							}
							height += linePitch;
						}
					}else{
						width[0] += charWidth[len];
						if (width[0] > printWidth) {
							width[0] = charWidth[len];
							height += linePitch;
						}
					}

					if(height>nExtHeight){
						height=nExtHeight;
						bSplit=true;
						break;
					}
				}
			}

			if(bSplit){
				strSplitData[0]=data.substring(0, i);
				strSplitData[1]=data.substring(i);
			}

			height = (int)MAX((long)height,(long)nMaxHeight);
			return height;
		}
	}

	//스크립트 헤더 출력 함수
	private void getScriptHeader(String paper, String size, String value, String orient, String margin) throws Exception{
		//GetScriptHeader_AutoCode
		manager.scriptWrite("AIReport", "scriptVersion|docVersion|style|title", "32|0|Temporary.style|통계", false);
	}

	private void getSheetPaperInfo(String paper, String size, String value, String orient, String margin) throws Exception{
		//GetSheetPaperInfo_AutoCode
		manager.scriptWrite("PaperInfo", "name|size|value|orientation|margin", paper+"|"+size+"|"+value+"|"+orient+"|"+margin, true);
	}

	private void initSheetVariant(int constStartX, int constStartY, int constEndX, int constEndY, boolean bFirstFrame){
		//InitSheetVariant_AutoCode
		if(bFirstFrame){
			nStartPage=nMaxPage+1;
			nYLastPos=0;
		}
		nPageNum=nStartPage;
		nYStartPos=constStartY;
		nYEndPos=constEndY;
		nYCurPos=nYStartPos;
		nXStartPos=constStartX;
		nXEndPos=constEndX;
		CELL_OBJECT=0;
		DRAW_OBJECT=1;
		nXCurPos=nXStartPos;
	}

	private void initChildSheetVariant(int constStartX, int constStartY, int constEndX, int constEndY, boolean bIsMultiFrame, boolean bIsFirstFrame){
		//InitChildSheetVariant_AutoCode
		nXStartPos=constStartX;
		nXEndPos=constEndX;
		nXCurPos=nXStartPos;
		nYStartPos=constStartY;
		nYEndPos=constEndY;

		if(bIsMultiFrame){
			if(bIsFirstFrame){
				nStartPage=nPageNum;
				nYSavePos=nYCurPos;
				nYLastPos=0;
			}else{
				nPageNum=nStartPage;
				nYCurPos=nYSavePos;
			}
		}else{
			nStartPage=nPageNum;
		}
	}

	//Empty Row만으로 구성되어 출력 위치를 조정하기 위한 VoidBand 함수
	//nRangePos - VoidBand의 출력 영역
	//nIndex - PageSkip 함수 호출시 전달할 쉬트 인덱스
	private boolean voidBandNoneData(int nRangePos, int nIndex) throws Exception{
		//VoidBandNoneData_AutoCode
		int nTestPos;
		nTestPos=nYCurPos+nRangePos;
		if(isPageSkip(nTestPos)){
			pageSkip(nIndex);
			return true;
		}else{
			nYCurPos=nYCurPos+nRangePos;
			return false;
		}
	}

	private String Get0(String str){
		//Get0_AutoCode
		if(str==null){
			return "0";
		}else{
			if(str.equals("")){
				return "0";
			}else{
				return str;
			}
		}
	}

	private String GetB(String str){
		//GetB_AutoCode
		if(str==null){
			return "";
		}else{
			return str;
		}
	}

	private double SUM(double accVal, double tmpVal){
		//SUM(double, double)_AutoCode
		return(accVal+tmpVal);
	}

	private double SUM(double accVal, long tmpVal){
		//SUM(double, long)_AutoCode
		return(accVal+(double)tmpVal);
	}

	private long SUM(long accVal, long tmpVal){
		//SUM(long, long)_AutoCode
		return(accVal+tmpVal);
	}

	private double SUM(long accVal, double tmpVal){
		//SUM(long, double)_AutoCode
		return((double)accVal+tmpVal);
	}

	private long COUNT(long accuCNT){
		//COUNT_AutoCode
		return ++accuCNT;
	}

	private long MIN(long maxV, long maxTempV){
		//MIN(long, long)_AutoCode
		if(maxV<=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MIN(long maxV, double maxTempV){
		//MIN(long, double)_AutoCode
		if((double)maxV<=maxTempV){return (double)maxV;}
		else{return maxTempV;}
	}

	private double MIN(double maxV, double maxTempV){
		//MIN(double, double)_AutoCode
		if(maxV<=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MIN(double maxV, long maxTempV){
		//MIN(double, long)_AutoCode
		if(maxV<=maxTempV){return maxV;}
		else{return (double)maxTempV;}
	}

	private long MAX(long maxV, long maxTempV){
		//MAX(long, long)_AutoCode
		if(maxV>=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MAX(long maxV, double maxTempV){
		//MAX(long, double)_AutoCode
		if((double)maxV>=maxTempV){return (double)maxV;}
		else{return maxTempV;}
	}

	private double MAX(double maxV, double maxTempV){
		//MAX(double, double)_AutoCode
		if(maxV>=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MAX(double maxV, long maxTempV){
		//MAX(double, long)_AutoCode
		if(maxV>=maxTempV){return maxV;}
		else{return (double)maxTempV;}
	}

	private double AVG(double sumVal, long cntVal){
		//AVG(double, long)_AutoCode
		return(sumVal/cntVal);
	}

	private double AVG(long sumVal, long cntVal){
		//AVG(long, long)_AutoCode
		return((double)sumVal/(double)cntVal);
	}

	private String aiReplace(String strAll, String strSrc, String strDest) {
		//AIReplace_AutoCode
		int st = 0, ed = 0;
		final int size = strAll.length();
		ed = strAll.indexOf(strSrc);
		if (ed == -1) return strAll;

		StringBuffer buf = new StringBuffer(size);
		final int len =  strSrc.length();
		do {
			buf.append(strAll.substring(st, ed));
			buf.append(strDest);
			ed += len;
			st = ed;
		} while ((ed = strAll.indexOf(strSrc, ed)) != -1);
		if (st < size) {
			buf.append(strAll.substring(st));
		}
		return buf.toString();
	}

	private String toDate() {
		//ToDate_AutoCode
		SimpleDateFormat dateFormat=new SimpleDateFormat("'#SERVERDATE#'yyyy/MM/dd/HH/mm/ss");
		java.util.Date currentDate = new java.util.Date();
		return dateFormat.format(currentDate);
	}

	final String toKor (String en){
		//ToKor_AutoCode
		if(en==null){
			return "";
		}
		try{
			return new String(en.getBytes("ISO-8859-1"), "utf-8");
		}catch(Exception e){return en;}
	}

	private void objectWrite(int type, int left, int top, int width, int height, String data, String name, String style) throws Exception {
		//ObjectWrite_AutoCode
		manager.scriptWrite(type, left, top, width, height, data, name, style);
	}

	private void propertyWrite(int type, String name, String property, String style) throws Exception {
		//PropertyWrite_AutoCode
		manager.scriptWrite(type, name, property, style);
	}

	private void pageWrite(int pageNum) throws Exception {
		//PageWrite_AutoCode
		manager.scriptWrite("Page", "number", Integer.toString(pageNum), true);
	}

	private void objectCellWrite(String name, String data, int nMoveX, int nMoveY) throws Exception {
		objectWrite(CELL_OBJECT, nMoveX+(nXCurPos+mapLeft.get(name)), nMoveY+(nYCurPos+mapTop.get(name)), mapWidth.get(name), mapHeight.get(name), data, name, mapStyle.get(name));
	}

	public String checkParam(String param) {
		param = param.replace("'", "");
		param = param.replace(";", "");
		param = param.replace("|", "");
		param = param.replace(":", "");
		param = param.replace("+", "");
		param = param.replace("\"", "");
		param = param.replace("\\", "");
		param = param.replace("--", "");
		param = param.replace("/", "");
		param = param.replaceAll("(?i)select", "");
		param = param.replaceAll("(?i)union", "");
		param = param.replaceAll("(?i)delete", "");
		param = param.replaceAll("(?i)update", "");
		param = param.replaceAll("(?i)insert", "");
		param = param.replaceAll("(?i)create", "");
		param = param.replaceAll("(?i)alter", "");
		param = param.replaceAll("(?i)drop", "");
		param = param.replaceAll("(?i)grant", "");
		param = param.replaceAll("(?i)revoke", "");
		param = param.replaceAll("(?i)merge", "");
		return param;
	}

	public String checkAITag(String strText) {
		strText = strText.replace("AI{P}", "^");
		strText = strText.replace("AI{F}", "@");
		strText = strText.replace("AI{S}", "#");
		strText = strText.replace("AI{E}", "=");
		return strText;
	}

	//셀 Rect, Style값 Map 저장
	public void setCellInfoMap_Internal(String name, int left, int top, int width, int height, String style) throws Exception {
		if( left != -1 ) {
			mapLeft.put(name, left);
		}
		if( top != -1 ) {
			mapTop.put(name, top);
		}
		if( width != -1 ) {
			mapWidth.put(name, width);
		}
		if( height != -1 ) {
			mapHeight.put(name, height);
		}
		if( style != null && !style.equals("") ) {
			mapStyle.put(name, style);
		}
	}

	//셀 Rect, Style값 저장
	public void setCellInfoMap() throws Exception {
		mapLeft = new HashMap<String, Integer>();
		mapTop = new HashMap<String, Integer>();
		mapWidth = new HashMap<String, Integer>();
		mapHeight = new HashMap<String, Integer>();
		mapStyle = new HashMap<String, String>();
		setCellInfoMap_Internal("sheet10_A1", 0, 0, 24, 20, "cell_style_0");
		setCellInfoMap_Internal("sheet10_A2", 0, 0, 256, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_J2", 256, 0, 29, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_K2", 285, 0, 29, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_L2", 314, 0, 29, 27, "cell_style_2");
		setCellInfoMap_Internal("sheet10_M2", 343, 0, 29, 27, "cell_style_2");
		setCellInfoMap_Internal("sheet10_N2", 372, 0, 29, 27, "cell_style_2");
		setCellInfoMap_Internal("sheet10_O2", 401, 0, 29, 27, "cell_style_2");
		setCellInfoMap_Internal("sheet10_P2", 430, 0, 29, 27, "cell_style_2");
		setCellInfoMap_Internal("sheet10_Q2", 459, 0, 28, 27, "cell_style_2");
		setCellInfoMap_Internal("sheet10_R2", 487, 0, 28, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_S2", 515, 0, 28, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_T2", 543, 0, 28, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_U2", 571, 0, 28, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_V2", 599, 0, 28, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_W2", 627, 0, 28, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_X2", 655, 0, 28, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_Y2", 683, 0, 28, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_B22", 24, 0, 348, 20, "cell_style_4");
		setCellInfoMap_Internal("sheet10_N22", 372, 0, 339, 20, "cell_style_5");
		setCellInfoMap_Internal("sheet10_B23", 24, 0, 348, 20, "cell_style_6");
		setCellInfoMap_Internal("sheet10_N23", 372, 0, 339, 20, "cell_style_7");
		setCellInfoMap_Internal("sheet10_B24", 24, 0, 29, 20, "cell_style_8");
	}

	private ResultSet acquireResultSet(CallableStatement cstmt, int cursorIdx) throws SQLException {
		if (cstmt.execute()) {
			if (cursorIdx == -1) {
				return (cstmt.getResultSet());
			} else {
				return ((ResultSet) cstmt.getObject(cursorIdx));
			}
		} else {
			int count;
			if ((count = cstmt.getUpdateCount()) == -1) {
				if (cursorIdx == -1) {
					throw (new UnsupportedOperationException("None result"));
				} else {
					return ((ResultSet) cstmt.getObject(cursorIdx));
				}
			}
			while (true) {
				if (cstmt.getMoreResults()) {
					if (cursorIdx == -1) {
						return (cstmt.getResultSet());
					} else {
						return ((ResultSet) cstmt.getObject(cursorIdx));
					}
				} else if ((count = cstmt.getUpdateCount()) == -1) {
					if (cursorIdx == -1) {
						throw (new UnsupportedOperationException("None result-2"));
					} else {
						return ((ResultSet) cstmt.getObject(cursorIdx));
					}
				}
			}
		}
	}
}
%>
