<%
/************************************************************************************
Generated by AIDesigner 5.6.0.3
************************************************************************************
보고서 제목 : 통계
작성일 : 2016년4월22일 10시42분9초
수정일 : 2016년8월16일 17시30분19초
작성자 :
************************************************************************************/
%>

<%@ page pageEncoding="UTF-8" %>
<%@ page contentType="text/html; charset=utf-8" %>

<%@ page import="java.sql.*,java.io.*,java.lang.*,java.text.*,java.util.*,java.net.URL" %>
<%@ page import="com.activeintra.manager.*" %>
<%@ page import="com.activeintra.url.*" %>
<%@ page import="com.activeintra.util.uds.*" %>
<%@ page import="org.apache.log4j.Logger" %>
<%@ page import="org.apache.log4j.PropertyConfigurator" %>


<%
Object[] userObj = null;
HttpParameterDecoder decoder = HttpParameterDecoder.newInstance(request, application);
request.setAttribute("paramsDecoder", decoder);

String reportMode = decoder.getParameter("reportMode");
String reportParams = decoder.getParameter("reportParams");
if(reportMode!=null){
	if(reportMode.equals("PDF")){
		if(reportParams == null || reportParams.toLowerCase().indexOf("pdfserversave:true") == -1){
			out.clear();
			out=pageContext.pushBody();
		}
	}
	else if(reportMode.equals("EXCEL")){
		if(reportParams == null || reportParams.toLowerCase().indexOf("excelserversave:true") == -1){
			out.clear();
			out=pageContext.pushBody();
		}
	}
	else if(reportMode.equals("AR5")){
		out.clear();
		out=pageContext.pushBody();
	}
}

ReportHandler handler = new ReportHandler(pageContext, request, response, userObj, decoder);
handler.service(out);
handler = null;
%>

<%!
private ReportInitializer initializer;
//보고서 초기화 - 한번만 실행되고 사용자 Request에서 반복사용가능한 코드를 기술
public void jspInit() {
	initializer = new ReportInitializer(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
	//수정되지 않는 정적 Query변수들을 초기화
	//sql_getJnspJipConsultingDay
	StringBuilder sql_getJnspJipConsultingDay = new StringBuilder();
	sql_getJnspJipConsultingDay.setLength(0);
	sql_getJnspJipConsultingDay.append("SELECT ");
	sql_getJnspJipConsultingDay.append("				A.BOARD_ID, ");
	sql_getJnspJipConsultingDay.append("				DATE_FORMAT(A.FRST_REGIST_PNTTM,'%m월%d일') AS DAY, ");
	sql_getJnspJipConsultingDay.append("				COUNT(0) AS CNT ");
	sql_getJnspJipConsultingDay.append("			FROM JMY_BOARD_ARTICLE AS A ");
	sql_getJnspJipConsultingDay.append("			LEFT JOIN JMY_BOARD AS B ");
	sql_getJnspJipConsultingDay.append("				ON A.BOARD_ID = B.BOARD_ID ");
	sql_getJnspJipConsultingDay.append("			WHERE 1 = 1 ");
	sql_getJnspJipConsultingDay.append("				AND A.BOARD_ID >= '00024' ");
	sql_getJnspJipConsultingDay.append("				AND A.BOARD_ID <= '00027' ");
	sql_getJnspJipConsultingDay.append("				AND A.DATA04 = '2' ");
	sql_getJnspJipConsultingDay.append("				AND A.FRST_REGIST_PNTTM >= DATE_ADD(NOW(), INTERVAL -11 DAY) ");
	sql_getJnspJipConsultingDay.append("				AND A.FRST_REGIST_PNTTM <= CONCAT(DATE_FORMAT(A.FRST_REGIST_PNTTM, NOW())) ");
	sql_getJnspJipConsultingDay.append("				GROUP BY DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년%m월%d일') ");
	sql_getJnspJipConsultingDay.append("				ORDER BY DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년%m월%d일') ASC ");
	initializer.prepareQuery("sql_getJnspJipConsultingDay", sql_getJnspJipConsultingDay.toString());

	//sql_getJnspJipConsultingDayTt
	StringBuilder sql_getJnspJipConsultingDayTt = new StringBuilder();
	sql_getJnspJipConsultingDayTt.setLength(0);
	sql_getJnspJipConsultingDayTt.append("SELECT ");
	sql_getJnspJipConsultingDayTt.append("				A.BOARD_ID, ");
	sql_getJnspJipConsultingDayTt.append("				DATE_FORMAT(A.FRST_REGIST_PNTTM,'%m월%d일') AS DAY, ");
	sql_getJnspJipConsultingDayTt.append("				COUNT(0) AS CNT ");
	sql_getJnspJipConsultingDayTt.append("			FROM JMY_BOARD_ARTICLE AS A ");
	sql_getJnspJipConsultingDayTt.append("			LEFT JOIN JMY_BOARD AS B ");
	sql_getJnspJipConsultingDayTt.append("				ON A.BOARD_ID = B.BOARD_ID ");
	sql_getJnspJipConsultingDayTt.append("			WHERE 1 = 1 ");
	sql_getJnspJipConsultingDayTt.append("				AND A.BOARD_ID >= '00024' ");
	sql_getJnspJipConsultingDayTt.append("				AND A.BOARD_ID <= '00027' ");
	sql_getJnspJipConsultingDayTt.append("				AND A.DATA04 = '2' ");
	sql_getJnspJipConsultingDayTt.append("				AND A.FRST_REGIST_PNTTM >= DATE_ADD(NOW(), INTERVAL -11 DAY) ");
	sql_getJnspJipConsultingDayTt.append("				AND A.FRST_REGIST_PNTTM <= CONCAT(DATE_FORMAT(A.FRST_REGIST_PNTTM, NOW())) ");
	sql_getJnspJipConsultingDayTt.append("				GROUP BY DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년%m월%d일') ");
	sql_getJnspJipConsultingDayTt.append("				ORDER BY DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년%m월%d일') ASC ");
	initializer.prepareQuery("sql_getJnspJipConsultingDayTt", sql_getJnspJipConsultingDayTt.toString());

	//sql_getJnspJipConsultingDayTb
	StringBuilder sql_getJnspJipConsultingDayTb = new StringBuilder();
	sql_getJnspJipConsultingDayTb.setLength(0);
	sql_getJnspJipConsultingDayTb.append("SELECT ");
	sql_getJnspJipConsultingDayTb.append("				A.BOARD_ID, ");
	sql_getJnspJipConsultingDayTb.append("				DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년%m월%d일') AS DAY, ");
	sql_getJnspJipConsultingDayTb.append("				COUNT(0) AS CNT ");
	sql_getJnspJipConsultingDayTb.append("			FROM JMY_BOARD_ARTICLE AS A ");
	sql_getJnspJipConsultingDayTb.append("			LEFT JOIN JMY_BOARD AS B ");
	sql_getJnspJipConsultingDayTb.append("				ON A.BOARD_ID = B.BOARD_ID ");
	sql_getJnspJipConsultingDayTb.append("			WHERE 1 = 1 ");
	sql_getJnspJipConsultingDayTb.append("				AND A.BOARD_ID >= '00024' ");
	sql_getJnspJipConsultingDayTb.append("				AND A.BOARD_ID <= '00027' ");
	sql_getJnspJipConsultingDayTb.append("				AND A.DATA04 = '2' ");
	sql_getJnspJipConsultingDayTb.append("				AND A.FRST_REGIST_PNTTM >= DATE_ADD(NOW(), INTERVAL -30 DAY) ");
	sql_getJnspJipConsultingDayTb.append("				AND A.FRST_REGIST_PNTTM <= CONCAT(DATE_FORMAT(A.FRST_REGIST_PNTTM, NOW())) ");
	sql_getJnspJipConsultingDayTb.append("				GROUP BY DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년%m월%d일') ");
	sql_getJnspJipConsultingDayTb.append("				ORDER BY DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년%m월%d일') DESC ");
	initializer.prepareQuery("sql_getJnspJipConsultingDayTb", sql_getJnspJipConsultingDayTb.toString());

	//sql_getJnspJipConsultingMon
	StringBuilder sql_getJnspJipConsultingMon = new StringBuilder();
	sql_getJnspJipConsultingMon.setLength(0);
	sql_getJnspJipConsultingMon.append("SELECT ");
	sql_getJnspJipConsultingMon.append("				A.BOARD_ID, ");
	sql_getJnspJipConsultingMon.append("				DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년%m월') AS DAY, ");
	sql_getJnspJipConsultingMon.append("				COUNT(0) AS CNT ");
	sql_getJnspJipConsultingMon.append("			FROM JMY_BOARD_ARTICLE AS A ");
	sql_getJnspJipConsultingMon.append("			LEFT JOIN JMY_BOARD AS B ");
	sql_getJnspJipConsultingMon.append("				ON A.BOARD_ID = B.BOARD_ID ");
	sql_getJnspJipConsultingMon.append("			WHERE 1 = 1 ");
	sql_getJnspJipConsultingMon.append("				AND A.BOARD_ID >= '00024' ");
	sql_getJnspJipConsultingMon.append("				AND A.BOARD_ID <= '00027' ");
	sql_getJnspJipConsultingMon.append("				AND A.DATA04 = '2' ");
	sql_getJnspJipConsultingMon.append("				AND A.FRST_REGIST_PNTTM >= DATE_ADD(NOW(), INTERVAL -13 MONTH) ");
	sql_getJnspJipConsultingMon.append("				AND A.FRST_REGIST_PNTTM <= CONCAT(DATE_FORMAT(A.FRST_REGIST_PNTTM, NOW())) ");
	sql_getJnspJipConsultingMon.append("				GROUP BY DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년%m월') ");
	sql_getJnspJipConsultingMon.append("				ORDER BY DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년%m월') ASC ");
	initializer.prepareQuery("sql_getJnspJipConsultingMon", sql_getJnspJipConsultingMon.toString());

	//sql_getJnspJipConsultingMonTt
	StringBuilder sql_getJnspJipConsultingMonTt = new StringBuilder();
	sql_getJnspJipConsultingMonTt.setLength(0);
	sql_getJnspJipConsultingMonTt.append("SELECT ");
	sql_getJnspJipConsultingMonTt.append("				A.BOARD_ID, ");
	sql_getJnspJipConsultingMonTt.append("				DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년%m월') AS DAY, ");
	sql_getJnspJipConsultingMonTt.append("				COUNT(0) AS CNT ");
	sql_getJnspJipConsultingMonTt.append("			FROM JMY_BOARD_ARTICLE AS A ");
	sql_getJnspJipConsultingMonTt.append("			LEFT JOIN JMY_BOARD AS B ");
	sql_getJnspJipConsultingMonTt.append("				ON A.BOARD_ID = B.BOARD_ID ");
	sql_getJnspJipConsultingMonTt.append("			WHERE 1 = 1 ");
	sql_getJnspJipConsultingMonTt.append("				AND A.BOARD_ID >= '00024' ");
	sql_getJnspJipConsultingMonTt.append("				AND A.BOARD_ID <= '00027' ");
	sql_getJnspJipConsultingMonTt.append("				AND A.DATA04 = '2' ");
	sql_getJnspJipConsultingMonTt.append("				AND A.FRST_REGIST_PNTTM >= DATE_ADD(NOW(), INTERVAL -13 MONTH) ");
	sql_getJnspJipConsultingMonTt.append("				AND A.FRST_REGIST_PNTTM <= CONCAT(DATE_FORMAT(A.FRST_REGIST_PNTTM, NOW())) ");
	sql_getJnspJipConsultingMonTt.append("				GROUP BY DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년%m월') ");
	sql_getJnspJipConsultingMonTt.append("				ORDER BY DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년%m월') ASC ");
	initializer.prepareQuery("sql_getJnspJipConsultingMonTt", sql_getJnspJipConsultingMonTt.toString());

	//sql_getJnspJipConsultingMonTb
	StringBuilder sql_getJnspJipConsultingMonTb = new StringBuilder();
	sql_getJnspJipConsultingMonTb.setLength(0);
	sql_getJnspJipConsultingMonTb.append("SELECT ");
	sql_getJnspJipConsultingMonTb.append("				A.BOARD_ID, ");
	sql_getJnspJipConsultingMonTb.append("				DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년%m월') AS DAY, ");
	sql_getJnspJipConsultingMonTb.append("				COUNT(0) AS CNT ");
	sql_getJnspJipConsultingMonTb.append("			FROM JMY_BOARD_ARTICLE AS A ");
	sql_getJnspJipConsultingMonTb.append("			LEFT JOIN JMY_BOARD AS B ");
	sql_getJnspJipConsultingMonTb.append("				ON A.BOARD_ID = B.BOARD_ID ");
	sql_getJnspJipConsultingMonTb.append("			WHERE 1 = 1 ");
	sql_getJnspJipConsultingMonTb.append("				AND A.BOARD_ID >= '00024' ");
	sql_getJnspJipConsultingMonTb.append("				AND A.BOARD_ID <= '00027' ");
	sql_getJnspJipConsultingMonTb.append("				AND A.DATA04 = '2' ");
	sql_getJnspJipConsultingMonTb.append("				AND A.FRST_REGIST_PNTTM >= DATE_ADD(NOW(), INTERVAL -13 MONTH) ");
	sql_getJnspJipConsultingMonTb.append("				AND A.FRST_REGIST_PNTTM <= CONCAT(DATE_FORMAT(A.FRST_REGIST_PNTTM, NOW())) ");
	sql_getJnspJipConsultingMonTb.append("				GROUP BY DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년%m월') ");
	sql_getJnspJipConsultingMonTb.append("				ORDER BY DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년%m월') DESC ");
	initializer.prepareQuery("sql_getJnspJipConsultingMonTb", sql_getJnspJipConsultingMonTb.toString());

	//sql_getJnspJipConsultingYear
	StringBuilder sql_getJnspJipConsultingYear = new StringBuilder();
	sql_getJnspJipConsultingYear.setLength(0);
	sql_getJnspJipConsultingYear.append("SELECT ");
	sql_getJnspJipConsultingYear.append("				A.BOARD_ID, ");
	sql_getJnspJipConsultingYear.append("				DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년') AS DAY, ");
	sql_getJnspJipConsultingYear.append("				COUNT(0) AS CNT ");
	sql_getJnspJipConsultingYear.append("			FROM JMY_BOARD_ARTICLE AS A ");
	sql_getJnspJipConsultingYear.append("			LEFT JOIN JMY_BOARD AS B ");
	sql_getJnspJipConsultingYear.append("				ON A.BOARD_ID = B.BOARD_ID ");
	sql_getJnspJipConsultingYear.append("			WHERE 1 = 1 ");
	sql_getJnspJipConsultingYear.append("				AND A.BOARD_ID >= '00024' ");
	sql_getJnspJipConsultingYear.append("				AND A.BOARD_ID <= '00027' ");
	sql_getJnspJipConsultingYear.append("				AND A.DATA04 = '2' ");
	sql_getJnspJipConsultingYear.append("				AND A.FRST_REGIST_PNTTM >= DATE_ADD(NOW(), INTERVAL -6 YEAR) ");
	sql_getJnspJipConsultingYear.append("				AND A.FRST_REGIST_PNTTM <= CONCAT(DATE_FORMAT(A.FRST_REGIST_PNTTM, NOW())) ");
	sql_getJnspJipConsultingYear.append("				GROUP BY DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년') ");
	sql_getJnspJipConsultingYear.append("				ORDER BY DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년') ASC ");
	initializer.prepareQuery("sql_getJnspJipConsultingYear", sql_getJnspJipConsultingYear.toString());

	//sql_getJnspJipConsultingYearTt
	StringBuilder sql_getJnspJipConsultingYearTt = new StringBuilder();
	sql_getJnspJipConsultingYearTt.setLength(0);
	sql_getJnspJipConsultingYearTt.append("SELECT ");
	sql_getJnspJipConsultingYearTt.append("				A.BOARD_ID, ");
	sql_getJnspJipConsultingYearTt.append("				DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년') AS DAY, ");
	sql_getJnspJipConsultingYearTt.append("				COUNT(0) AS CNT ");
	sql_getJnspJipConsultingYearTt.append("			FROM JMY_BOARD_ARTICLE AS A ");
	sql_getJnspJipConsultingYearTt.append("			LEFT JOIN JMY_BOARD AS B ");
	sql_getJnspJipConsultingYearTt.append("				ON A.BOARD_ID = B.BOARD_ID ");
	sql_getJnspJipConsultingYearTt.append("			WHERE 1 = 1 ");
	sql_getJnspJipConsultingYearTt.append("				AND A.BOARD_ID >= '00024' ");
	sql_getJnspJipConsultingYearTt.append("				AND A.BOARD_ID <= '00027' ");
	sql_getJnspJipConsultingYearTt.append("				AND A.DATA04 = '2' ");
	sql_getJnspJipConsultingYearTt.append("				AND A.FRST_REGIST_PNTTM >= DATE_ADD(NOW(), INTERVAL -6 YEAR) ");
	sql_getJnspJipConsultingYearTt.append("				AND A.FRST_REGIST_PNTTM <= CONCAT(DATE_FORMAT(A.FRST_REGIST_PNTTM, NOW())) ");
	sql_getJnspJipConsultingYearTt.append("				GROUP BY DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년') ");
	sql_getJnspJipConsultingYearTt.append("				ORDER BY DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년') ASC ");
	initializer.prepareQuery("sql_getJnspJipConsultingYearTt", sql_getJnspJipConsultingYearTt.toString());

	//sql_getJnspJipConsultingYearTb
	StringBuilder sql_getJnspJipConsultingYearTb = new StringBuilder();
	sql_getJnspJipConsultingYearTb.setLength(0);
	sql_getJnspJipConsultingYearTb.append("SELECT ");
	sql_getJnspJipConsultingYearTb.append("				A.BOARD_ID, ");
	sql_getJnspJipConsultingYearTb.append("				DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년') AS DAY, ");
	sql_getJnspJipConsultingYearTb.append("				COUNT(0) AS CNT ");
	sql_getJnspJipConsultingYearTb.append("			FROM JMY_BOARD_ARTICLE AS A ");
	sql_getJnspJipConsultingYearTb.append("			LEFT JOIN JMY_BOARD AS B ");
	sql_getJnspJipConsultingYearTb.append("				ON A.BOARD_ID = B.BOARD_ID ");
	sql_getJnspJipConsultingYearTb.append("			WHERE 1 = 1 ");
	sql_getJnspJipConsultingYearTb.append("				AND A.BOARD_ID >= '00024' ");
	sql_getJnspJipConsultingYearTb.append("				AND A.BOARD_ID <= '00027' ");
	sql_getJnspJipConsultingYearTb.append("				AND A.DATA04 = '2' ");
	sql_getJnspJipConsultingYearTb.append("				AND A.FRST_REGIST_PNTTM >= DATE_ADD(NOW(), INTERVAL -6 YEAR) ");
	sql_getJnspJipConsultingYearTb.append("				AND A.FRST_REGIST_PNTTM <= CONCAT(DATE_FORMAT(A.FRST_REGIST_PNTTM, NOW())) ");
	sql_getJnspJipConsultingYearTb.append("				GROUP BY DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년') ");
	sql_getJnspJipConsultingYearTb.append("				ORDER BY DATE_FORMAT(A.FRST_REGIST_PNTTM,'%Y년') DESC ");
	initializer.prepareQuery("sql_getJnspJipConsultingYearTb", sql_getJnspJipConsultingYearTb.toString());
}

private Logger logger = Logger.getLogger("com.activeintra");
class ReportHandler{
	//공통 변수 선언
	private Object[] userObj = null;
	private int nStartPage;		//각 쉬트별 시작 페이지 저장
	private int nMaxPage;		//한 쉬트가 실행된 후 생성된 최대 페이지 번호 저장
	private int nPageNum;		//현재 페이지 번호
	private int nYStartPos;		//쉬트에서 Y 시작 좌표
	private int nYEndPos;		//쉬트에서 Y 끝 좌표
	private int nYCurPos;		//현재 Y 좌표
	private int nYSavePos;		//연결된 멀티 프레임 쉬트에서 시작 Y 좌표 저장
	private int nYLastPos;		//연결된 멀티 프레임 쉬트에서 각 프레임의 마지막 Y 좌표 저장
	private int nXStartPos;		//쉬트에서 X 시작 좌표
	private int nXEndPos;		//쉬트에서 X 끝 좌표
	private int nXCurPos;		//현재 X 좌표
	private int nXSavePos;		//연결된 멀티 프레임 쉬트에서 시작 X 좌표 저장
	private int  nXLastPos;		//연결된 멀티 프레임 쉬트에서 각 프레임의 마지막 X 좌표 저장
	private boolean bIsBeforePageSkip;		//조건 밴드에서 페이지 넘기기 여부 판단
	private int nLoopRef;		//절대 양식에서 루프 참조 변수
	private int CELL_OBJECT = 0;
	private int DRAW_OBJECT = 1;
	private String isEmpty="";		//빈 문자열 비교에 사용
	private Map<String, String> mapParam;

	private int nBandRepeatType;	//1이면 반복밴드 가로 반복
	private int nBandWidth;		//반복밴드의 가로 폭
	private int nBandOffset;		//반복밴드 가로 반복 offset값
	private int nYBandStart;		//반복밴드 가로 반복 Y 시작 좌표
	private int nYBandEnd;		//반복밴드 가로 반복 Y 끝 좌표
	private int nHorRepeatNum;		//반복밴드 가로 반복 횟수
	private int nHorRepeatCnt;		//반복밴드 가로 반복 횟수 카운팅
	private Map<String, Integer> mapLeft;		//셀 Left
	private Map<String, Integer> mapTop;		//셀 Top
	private Map<String, Integer> mapWidth;		//셀 Width
	private Map<String, Integer> mapHeight;		//셀 Height
	private Map<String, String> mapStyle;		//셀 Style
	private HttpServletRequest request;
	private HttpServletResponse response;
	private PageContext pageContext;
	private JspWriter out;
	private HttpParameterDecoder decoder;

	private AIScriptManager manager;
	private String reportMode="AIScript";
	private String pdfFilename="";
	private String excelFilename="";

	//-----데이터 변수 선언-----
	long sheet10_A1 = 0L;
	String sheet10_A2 = "";
	String AI_CHART_OBJ41;
	String sheet10_B22 = "";
	String sheet10_N22 = "";
	String sheet10_B23 = "";
	long sheet10_N23 = 0L;
	String sheet10_B24 = "";

	//-----Connection, Statement, ResultSet 객체 선언-----
	private Connection conn_jnsp; 	 //jnsp Connection 객체
	private java.sql.PreparedStatement stat_getJnspJipConsultingDay;		//ResultSet getJnspJipConsultingDay 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipConsultingDay;		//ResultSet getJnspJipConsultingDay 객체
	private java.sql.PreparedStatement stat_getJnspJipConsultingDayTt;		//ResultSet getJnspJipConsultingDayTt 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipConsultingDayTt;		//ResultSet getJnspJipConsultingDayTt 객체
	private java.sql.PreparedStatement stat_getJnspJipConsultingDayTb;		//ResultSet getJnspJipConsultingDayTb 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipConsultingDayTb;		//ResultSet getJnspJipConsultingDayTb 객체
	private java.sql.PreparedStatement stat_getJnspJipConsultingMon;		//ResultSet getJnspJipConsultingMon 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipConsultingMon;		//ResultSet getJnspJipConsultingMon 객체
	private java.sql.PreparedStatement stat_getJnspJipConsultingMonTt;		//ResultSet getJnspJipConsultingMonTt 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipConsultingMonTt;		//ResultSet getJnspJipConsultingMonTt 객체
	private java.sql.PreparedStatement stat_getJnspJipConsultingMonTb;		//ResultSet getJnspJipConsultingMonTb 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipConsultingMonTb;		//ResultSet getJnspJipConsultingMonTb 객체
	private java.sql.PreparedStatement stat_getJnspJipConsultingYear;		//ResultSet getJnspJipConsultingYear 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipConsultingYear;		//ResultSet getJnspJipConsultingYear 객체
	private java.sql.PreparedStatement stat_getJnspJipConsultingYearTt;		//ResultSet getJnspJipConsultingYearTt 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipConsultingYearTt;		//ResultSet getJnspJipConsultingYearTt 객체
	private java.sql.PreparedStatement stat_getJnspJipConsultingYearTb;		//ResultSet getJnspJipConsultingYearTb 객체를 생성하기 위한 PreparedStatement 객체
	private ResultSet getJnspJipConsultingYearTb;		//ResultSet getJnspJipConsultingYearTb 객체

	//-----SQL 변수 선언-----
	private StringBuilder sql_getJnspJipConsultingDay = new StringBuilder();		//ResultSet getJnspJipConsultingDay 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_getJnspJipConsultingDayTt = new StringBuilder();		//ResultSet getJnspJipConsultingDayTt 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_getJnspJipConsultingDayTb = new StringBuilder();		//ResultSet getJnspJipConsultingDayTb 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_getJnspJipConsultingMon = new StringBuilder();		//ResultSet getJnspJipConsultingMon 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_getJnspJipConsultingMonTt = new StringBuilder();		//ResultSet getJnspJipConsultingMonTt 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_getJnspJipConsultingMonTb = new StringBuilder();		//ResultSet getJnspJipConsultingMonTb 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_getJnspJipConsultingYear = new StringBuilder();		//ResultSet getJnspJipConsultingYear 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_getJnspJipConsultingYearTt = new StringBuilder();		//ResultSet getJnspJipConsultingYearTt 객체를 생성하기 위한 쿼리문 저장
	private StringBuilder sql_getJnspJipConsultingYearTb = new StringBuilder();		//ResultSet getJnspJipConsultingYearTb 객체를 생성하기 위한 쿼리문 저장

	//-----쿼리 필드 변수 선언-----
	//ResultSet getJnspJipConsultingDay 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipConsultingDay_BOARD_ID;
	private String getJnspJipConsultingDay_DAY;
	private long getJnspJipConsultingDay_CNT;

	//ResultSet getJnspJipConsultingDayTt 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipConsultingDayTt_BOARD_ID;
	private String getJnspJipConsultingDayTt_DAY;
	private long getJnspJipConsultingDayTt_CNT;

	//ResultSet getJnspJipConsultingDayTb 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipConsultingDayTb_BOARD_ID;
	private String getJnspJipConsultingDayTb_DAY;
	private long getJnspJipConsultingDayTb_CNT;

	//ResultSet getJnspJipConsultingMon 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipConsultingMon_BOARD_ID;
	private String getJnspJipConsultingMon_DAY;
	private long getJnspJipConsultingMon_CNT;

	//ResultSet getJnspJipConsultingMonTt 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipConsultingMonTt_BOARD_ID;
	private String getJnspJipConsultingMonTt_DAY;
	private long getJnspJipConsultingMonTt_CNT;

	//ResultSet getJnspJipConsultingMonTb 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipConsultingMonTb_BOARD_ID;
	private String getJnspJipConsultingMonTb_DAY;
	private long getJnspJipConsultingMonTb_CNT;

	//ResultSet getJnspJipConsultingYear 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipConsultingYear_BOARD_ID;
	private String getJnspJipConsultingYear_DAY;
	private long getJnspJipConsultingYear_CNT;

	//ResultSet getJnspJipConsultingYearTt 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipConsultingYearTt_BOARD_ID;
	private String getJnspJipConsultingYearTt_DAY;
	private long getJnspJipConsultingYearTt_CNT;

	//ResultSet getJnspJipConsultingYearTb 객체에서 필드 값을 받는 쿼리 필드 변수
	private String getJnspJipConsultingYearTb_BOARD_ID;
	private String getJnspJipConsultingYearTb_DAY;
	private long getJnspJipConsultingYearTb_CNT;

	//파라미터 변수 선언
	String userIdx_Param;
	String Idx_Param;

	//ReportHandler 생성자 함수
	ReportHandler(PageContext pageContext, HttpServletRequest request, HttpServletResponse response, Object[] userObj, HttpParameterDecoder decoder){
		this.pageContext = pageContext;
		this.request = request;
		this.response = response;
		this.userObj = userObj;
		this.decoder = decoder;
	}

	//ReportHandler 서비스 함수
	void service(JspWriter out) throws Exception{
		try{    //try 구문
			//변수 초기화
			this.out = out;
			nMaxPage = 0;   //nMaxPage 초기화

			nBandRepeatType=0;
			nBandWidth=0;
			nBandOffset=0;
			nYBandStart=0;
			nYBandEnd=0;
			nHorRepeatNum=0;
			nHorRepeatCnt=0;

			manager = new AIScriptManager(request, response, pageContext, out, logger, null);

			ServletContext context = pageContext.getServletContext();
			String temp = null;
			if(!context.getContextPath().equals("/"))
			temp = request.getRequestURI().replace(context.getContextPath(), "");
			else
			temp = request.getRequestURI();

			String path = temp.replace(".jsp", ".style");

			//셀 Rect, Style 값 저장
			setCellInfoMap();

			//파라미터 설정 함수 호출
			setParam();
			if(manager.open(reportMode, context.getRealPath(path)))
			{
				//스크립트 헤더 함수 호출
				getScriptHeader("A4", "2100x2970", "9", "VERTICAL", "56 70 56 70");

				//고정 데이터 초기화 함수 호출
				initConstVarient();

				//Connection 및 Statement 객체 생성 함수 호출
				createConnAndStateObject();

				//쿼리문 초기화 함수 호출
				initSQLConst();

				//쉬트 함수 호출
				//SHEET=Sheet1   FRAME=0 함수 호출
				executeSheet10();

				//---------------스크립트 종료---------------
				manager.scriptWrite("/AIReport", "", "", false);
				manager.close();
			}
		}catch(Exception e){    //catch 구문
			logger.error("---service function exception raised---");
			logger.error(e);
			throw e;
		}finally{    //finally 구문
			//DataSet Close
			cleanup(getJnspJipConsultingYearTb, stat_getJnspJipConsultingYearTb, null, null);
			cleanup(getJnspJipConsultingYearTt, stat_getJnspJipConsultingYearTt, null, null);
			cleanup(getJnspJipConsultingYear, stat_getJnspJipConsultingYear, null, null);
			cleanup(getJnspJipConsultingMonTb, stat_getJnspJipConsultingMonTb, null, null);
			cleanup(getJnspJipConsultingMonTt, stat_getJnspJipConsultingMonTt, null, null);
			cleanup(getJnspJipConsultingMon, stat_getJnspJipConsultingMon, null, null);
			cleanup(getJnspJipConsultingDayTb, stat_getJnspJipConsultingDayTb, null, null);
			cleanup(getJnspJipConsultingDayTt, stat_getJnspJipConsultingDayTt, null, null);
			cleanup(getJnspJipConsultingDay, stat_getJnspJipConsultingDay, null, null);
			cleanup(null, null, null, conn_jnsp);
		}    //end try
	}

	//-----쉬트 함수-----
	//-----SHEET=Sheet1   FRAME=Frame0 Start
	//-----폼 형식 : 상대 양식
	private void executeSheet10( ) throws Exception{
		//쉬트 초기화 함수 호출
		getSheetPaperInfo("User Define", "2700x2970", "256", "VERTICAL", "7 0 7 0");
		initSheetVariant(19, 12, 747, 831, true);

		//시작 페이지 번호 출력
		pageWrite(nPageNum);

		//밴드 함수 호출
		getScriptFromyyy(true, false);    //Void 밴드 호출
		getScriptFromview(true, true);    //Void 밴드 호출
		getScriptFromviewList(true, true);    //Void 밴드 호출
		getScriptFromTbList(true);    //반복 밴드 호출
		getScriptFromttttt(true, true);    //Void 밴드 호출

		//페이지 및 좌표 설정
		nMaxPage=(int)MAX((long)nMaxPage, (long)nPageNum);    //생성된 최대 페이지 번호 구하기
	}

	//-----밴드 함수-----
	//----yyy VoidBand Start----
	//----소속 쉬트 : SHEET=Sheet1    FRAME=Frame0
	//----밴드 이름 : yyy
	//----밴드 종류 : Void 밴드
	//----bIsFrist : 부모 밴드 함수나 쉬트 함수에서 최초로 호출될 때 true, 그 이후 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. true면 출력, false면 AI 스크립트를 생성하지 않음.
	//----nRepeatCnt : 부모 반복 밴드 수행 횟수와 연동 옵션 설정시 void 밴드가 수행할 반복 횟수 전달
	private void getScriptFromyyy(boolean bIsFirst, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=20;    //밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//DataSet 객체 생성
			//ResultSet getJnspJipConsultingYearTt 객체의 생성
			if(getJnspJipConsultingYearTt==null){
				getJnspJipConsultingYearTt = stat_getJnspJipConsultingYearTt.executeQuery();
			}else{
				getJnspJipConsultingYearTt.beforeFirst();
			}

			//데이터 fetch
			if(getJnspJipConsultingYearTt.next()){
				setFieldVariableFromgetJnspJipConsultingYearTt();	//ResultSet getJnspJipConsultingYearTt에서 필드 값 설정
			}else{
				setFieldInitFromgetJnspJipConsultingYearTt();	//ResultSet getJnspJipConsultingYearTt의 필드 값 초기화
			}

			//데이터 변수 초기화
			sheet10_A1=0L;

			//데이터 변수 할당
			sheet10_A1 = getJnspJipConsultingYearTt_CNT;
		}    //end if(bIsFirst)

		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 영역 검사
			if(isPageSkip(nYCurPos+nBandHeight)){
				pageSkip(10);
			}

			//스크립트 출력 함수 호출
			writeScriptyyy();

			//다음 출력 좌표 설정
			nYCurPos=nYCurPos+nBandHeight;
		}   //end if(bIsPrint)
	}

	//----view VoidBand Start----
	//----소속 쉬트 : SHEET=Sheet1    FRAME=Frame0
	//----밴드 이름 : view
	//----밴드 종류 : Void 밴드
	//----bIsFrist : 부모 밴드 함수나 쉬트 함수에서 최초로 호출될 때 true, 그 이후 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. true면 출력, false면 AI 스크립트를 생성하지 않음.
	//----nRepeatCnt : 부모 반복 밴드 수행 횟수와 연동 옵션 설정시 void 밴드가 수행할 반복 횟수 전달
	private void getScriptFromview(boolean bIsFirst, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=419;    //밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//데이터 변수 초기화
			AI_CHART_OBJ41="";

			//데이터 변수 할당
			sheet10_A2="    JIPBANK 활용통계";
			getChartDataAI_CHART_OBJ41( );
		}    //end if(bIsFirst)

		if(getJnspJipConsultingYearTt_CNT != 0 )
		{
		}
		else
		{
			return;
		}
		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 영역 검사
			if(isPageSkip(nYCurPos+nBandHeight)){
				pageSkip(10);
			}

			//스크립트 출력 함수 호출
			writeScriptview();

			//다음 출력 좌표 설정
			nYCurPos=nYCurPos+nBandHeight;
		}   //end if(bIsPrint)
	}

	//----viewList VoidBand Start----
	//----소속 쉬트 : SHEET=Sheet1    FRAME=Frame0
	//----밴드 이름 : viewList
	//----밴드 종류 : Void 밴드
	//----bIsFrist : 부모 밴드 함수나 쉬트 함수에서 최초로 호출될 때 true, 그 이후 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. true면 출력, false면 AI 스크립트를 생성하지 않음.
	//----nRepeatCnt : 부모 반복 밴드 수행 횟수와 연동 옵션 설정시 void 밴드가 수행할 반복 횟수 전달
	private void getScriptFromviewList(boolean bIsFirst, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=20;    //밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//데이터 변수 할당
			sheet10_B22="년별";
			sheet10_N22="상담 수";
		}    //end if(bIsFirst)

		if(getJnspJipConsultingYearTt_CNT != 0 )
		{
		}
		else
		{
			return;
		}
		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 영역 검사
			if(isPageSkip(nYCurPos+nBandHeight)){
				pageSkip(10);
			}

			//스크립트 출력 함수 호출
			writeScriptviewList();

			//다음 출력 좌표 설정
			nYCurPos=nYCurPos+nBandHeight;
		}   //end if(bIsPrint)
	}

	//-----TbList RepeatBand Start-----
	//-----소속 쉬트 : SHEET=Sheet1   FRAME=Frame0
	//-----밴드 이름 : TbList
	//-----밴드 종류 : 반복 밴드
	//-----bIsPrint : 감추기 속성 설정 여부 true면 출력, false면 스크립트를 생성하지 않음
	private void getScriptFromTbList(boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=20;    //밴드 출력 높이
		boolean bIsFirst=true;

		//데이터 변수 초기화
		sheet10_B23="";
		sheet10_N23=0L;

		//DataSet 객체 생성
		//ResultSet getJnspJipConsultingYearTb 객체의 생성
		if(getJnspJipConsultingYearTb==null){
			getJnspJipConsultingYearTb = stat_getJnspJipConsultingYearTb.executeQuery();
		}else{
			getJnspJipConsultingYearTb.beforeFirst();
		}

		if(getJnspJipConsultingYearTt_CNT != 0 )
		{
		}
		else
		{
			return;
		}
		//--while Loop Start--##
		while(getJnspJipConsultingYearTb.next()){   //자동으로 생성되는 반복 밴드의 루프문
			//데이터 fetch
			setFieldVariableFromgetJnspJipConsultingYearTb();	//RecordSet getJnspJipConsultingYearTb에서 필드 값 설정

			if(bIsFirst){   //밴드 호출 후 루프 내에서 한번 만 실행되는 코드
			}   //end if(bIsFirst)

			//데이터 변수 할당
			sheet10_B23 = getJnspJipConsultingYearTb_DAY;
			sheet10_N23 = getJnspJipConsultingYearTb_CNT;

			//AI 스크립트 출력
			if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
				if(isPageSkip(nYCurPos+nBandHeight)){   //스크립트 출력 영역 검사
					//페이지 스킵 함수 호출
					pageSkip(10);
				}   //end if(page skip test)

				//스크립트 출력 함수 호출
				writeScriptTbList();

				//다음 출력 좌표 설정
				nYCurPos=nYCurPos+nBandHeight;
			}   //end if(bIsPrint)

			//bIsFirst 및 출력 라인 설정
			bIsFirst=false;
		}   //while end

		if(bIsFirst){   //while 루프가 실행되지 않은 경우
		} else {   //while 루프가 실행된 경우
		}   //루프 외부 end if(bIsFirst)
	}

	//----ttttt VoidBand Start----
	//----소속 쉬트 : SHEET=Sheet1    FRAME=Frame0
	//----밴드 이름 : ttttt
	//----밴드 종류 : Void 밴드
	//----bIsFrist : 부모 밴드 함수나 쉬트 함수에서 최초로 호출될 때 true, 그 이후 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. true면 출력, false면 AI 스크립트를 생성하지 않음.
	//----nRepeatCnt : 부모 반복 밴드 수행 횟수와 연동 옵션 설정시 void 밴드가 수행할 반복 횟수 전달
	private void getScriptFromttttt(boolean bIsFirst, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=20;    //밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//데이터 변수 할당
			sheet10_B24="데이터가 없습니다";
		}    //end if(bIsFirst)

		if(getJnspJipConsultingYearTt_CNT == 0 )
		{
		}
		else
		{
			return;
		}
		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 영역 검사
			if(isPageSkip(nYCurPos+nBandHeight)){
				pageSkip(10);
			}

			//스크립트 출력 함수 호출
			writeScriptttttt();

			//다음 출력 좌표 설정
			nYCurPos=nYCurPos+nBandHeight;
		}   //end if(bIsPrint)
	}

	//-----스크립트 출력 함수-----
	//----yyy 스크립트 문 출력 함수----
	private void writeScriptyyy( ) throws Exception{
		//스크립트문 생성
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_A1"), nYCurPos+mapTop.get("sheet10_A1"), mapWidth.get("sheet10_A1"), mapHeight.get("sheet10_A1"), String.valueOf(sheet10_A1), "sheet10_A1", mapStyle.get("sheet10_A1"));
	}

	//----view 스크립트 문 출력 함수----
	private void writeScriptview( ) throws Exception{
		//스크립트문 생성
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_A2"), nYCurPos+mapTop.get("sheet10_A2"), mapWidth.get("sheet10_A2"), mapHeight.get("sheet10_A2"), sheet10_A2, "sheet10_A2", mapStyle.get("sheet10_A2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_J2"), nYCurPos+mapTop.get("sheet10_J2"), mapWidth.get("sheet10_J2"), mapHeight.get("sheet10_J2"), "", "sheet10_J2", mapStyle.get("sheet10_J2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_K2"), nYCurPos+mapTop.get("sheet10_K2"), mapWidth.get("sheet10_K2"), mapHeight.get("sheet10_K2"), "", "sheet10_K2", mapStyle.get("sheet10_K2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_L2"), nYCurPos+mapTop.get("sheet10_L2"), mapWidth.get("sheet10_L2"), mapHeight.get("sheet10_L2"), "", "sheet10_L2", mapStyle.get("sheet10_L2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_M2"), nYCurPos+mapTop.get("sheet10_M2"), mapWidth.get("sheet10_M2"), mapHeight.get("sheet10_M2"), "", "sheet10_M2", mapStyle.get("sheet10_M2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_N2"), nYCurPos+mapTop.get("sheet10_N2"), mapWidth.get("sheet10_N2"), mapHeight.get("sheet10_N2"), "", "sheet10_N2", mapStyle.get("sheet10_N2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_O2"), nYCurPos+mapTop.get("sheet10_O2"), mapWidth.get("sheet10_O2"), mapHeight.get("sheet10_O2"), "", "sheet10_O2", mapStyle.get("sheet10_O2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_P2"), nYCurPos+mapTop.get("sheet10_P2"), mapWidth.get("sheet10_P2"), mapHeight.get("sheet10_P2"), "", "sheet10_P2", mapStyle.get("sheet10_P2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_Q2"), nYCurPos+mapTop.get("sheet10_Q2"), mapWidth.get("sheet10_Q2"), mapHeight.get("sheet10_Q2"), "", "sheet10_Q2", mapStyle.get("sheet10_Q2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_R2"), nYCurPos+mapTop.get("sheet10_R2"), mapWidth.get("sheet10_R2"), mapHeight.get("sheet10_R2"), "", "sheet10_R2", mapStyle.get("sheet10_R2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_S2"), nYCurPos+mapTop.get("sheet10_S2"), mapWidth.get("sheet10_S2"), mapHeight.get("sheet10_S2"), "", "sheet10_S2", mapStyle.get("sheet10_S2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_T2"), nYCurPos+mapTop.get("sheet10_T2"), mapWidth.get("sheet10_T2"), mapHeight.get("sheet10_T2"), "", "sheet10_T2", mapStyle.get("sheet10_T2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_U2"), nYCurPos+mapTop.get("sheet10_U2"), mapWidth.get("sheet10_U2"), mapHeight.get("sheet10_U2"), "", "sheet10_U2", mapStyle.get("sheet10_U2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_V2"), nYCurPos+mapTop.get("sheet10_V2"), mapWidth.get("sheet10_V2"), mapHeight.get("sheet10_V2"), "", "sheet10_V2", mapStyle.get("sheet10_V2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_W2"), nYCurPos+mapTop.get("sheet10_W2"), mapWidth.get("sheet10_W2"), mapHeight.get("sheet10_W2"), "", "sheet10_W2", mapStyle.get("sheet10_W2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_X2"), nYCurPos+mapTop.get("sheet10_X2"), mapWidth.get("sheet10_X2"), mapHeight.get("sheet10_X2"), "", "sheet10_X2", mapStyle.get("sheet10_X2"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_Y2"), nYCurPos+mapTop.get("sheet10_Y2"), mapWidth.get("sheet10_Y2"), mapHeight.get("sheet10_Y2"), "", "sheet10_Y2", mapStyle.get("sheet10_Y2"));
		objectWrite(DRAW_OBJECT, nXCurPos, nYCurPos+33, 726, 362, AI_CHART_OBJ41, "AI_CHART_OBJ41", "draw_style_0");
	}

	//----viewList 스크립트 문 출력 함수----
	private void writeScriptviewList( ) throws Exception{
		//스크립트문 생성
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_B22"), nYCurPos+mapTop.get("sheet10_B22"), mapWidth.get("sheet10_B22"), mapHeight.get("sheet10_B22"), sheet10_B22, "sheet10_B22", mapStyle.get("sheet10_B22"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_N22"), nYCurPos+mapTop.get("sheet10_N22"), mapWidth.get("sheet10_N22"), mapHeight.get("sheet10_N22"), sheet10_N22, "sheet10_N22", mapStyle.get("sheet10_N22"));
	}

	//----TbList 스크립트 문 출력 함수----
	private void writeScriptTbList(  ) throws Exception{
		//스크립트문 생성
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_B23"), nYCurPos+mapTop.get("sheet10_B23"), mapWidth.get("sheet10_B23"), mapHeight.get("sheet10_B23"), sheet10_B23, "sheet10_B23", mapStyle.get("sheet10_B23"));
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_N23"), nYCurPos+mapTop.get("sheet10_N23"), mapWidth.get("sheet10_N23"), mapHeight.get("sheet10_N23"), String.valueOf(sheet10_N23), "sheet10_N23", mapStyle.get("sheet10_N23"));
	}

	//----ttttt 스크립트 문 출력 함수----
	private void writeScriptttttt( ) throws Exception{
		//스크립트문 생성
		objectWrite(CELL_OBJECT, nXCurPos+mapLeft.get("sheet10_B24"), nYCurPos+mapTop.get("sheet10_B24"), mapWidth.get("sheet10_B24"), mapHeight.get("sheet10_B24"), sheet10_B24, "sheet10_B24", mapStyle.get("sheet10_B24"));
	}

	private void getBgImageScriptEx(int nIndex) throws Exception{
	}

	//-----Connection 및 Statement 객체 생성 함수-----
	private void createConnAndStateObject() throws Exception{
		//jnsp Connection 객체 생성
		Class.forName("com.mysql.jdbc.Driver");
		conn_jnsp = DriverManager.getConnection("jdbc:mysql://jnsp.re.kr:3306/jnspcms??useUnicode=true&characterEncoding=utf-8", "jnspcms", "jnspcms!@12");
	}

	//-----ResultSet, PreparedStatement, Connection, CallableStatement Close 함수-----
	private void cleanup(Object rs, PreparedStatement st, CallableStatement cs, Connection conn){
		if(rs != null){
			try{
				if(rs instanceof ResultSet){
					((ResultSet)rs).close();
				}else if(rs instanceof com.activeintra.util.uds.AIDataSource){
					((com.activeintra.util.uds.AIDataSource)rs).close();
				}else if(rs instanceof com.activeintra.util.uds.XMLSetHandler){
					((com.activeintra.util.uds.XMLSetHandler)rs).close();
				}else if(rs instanceof com.activeintra.util.uds.CSVSetHandler){
					((com.activeintra.util.uds.CSVSetHandler)rs).close();
				}else if(rs instanceof com.activeintra.util.uds.JSONSetHandler){
					((com.activeintra.util.uds.JSONSetHandler)rs).close();
				}
			}
			catch(SQLException e){
				logger.error(e);
			}
		}

		if(st != null){
			try{
				st.close();
			}
			catch(SQLException e){
				logger.error(e);
			}
		}

		if(cs != null){
			try{
				cs.close();
			}
			catch(SQLException e){
				logger.error(e);
			}
		}

		if(conn != null){
			try{
				conn.close();
			}
			catch(SQLException e){
				logger.error(e);
			}
		}
	}

	//-----SQL문 변수 초기화 함수-----
	private void initSQLConst() throws Exception {
		stat_getJnspJipConsultingDay = initializer.configPreparedStatement("sql_getJnspJipConsultingDay", mapParam, conn_jnsp, null);

		stat_getJnspJipConsultingDayTt = initializer.configPreparedStatement("sql_getJnspJipConsultingDayTt", mapParam, conn_jnsp, null);

		stat_getJnspJipConsultingDayTb = initializer.configPreparedStatement("sql_getJnspJipConsultingDayTb", mapParam, conn_jnsp, null);

		stat_getJnspJipConsultingMon = initializer.configPreparedStatement("sql_getJnspJipConsultingMon", mapParam, conn_jnsp, null);

		stat_getJnspJipConsultingMonTt = initializer.configPreparedStatement("sql_getJnspJipConsultingMonTt", mapParam, conn_jnsp, null);

		stat_getJnspJipConsultingMonTb = initializer.configPreparedStatement("sql_getJnspJipConsultingMonTb", mapParam, conn_jnsp, null);

		stat_getJnspJipConsultingYear = initializer.configPreparedStatement("sql_getJnspJipConsultingYear", mapParam, conn_jnsp, null);

		stat_getJnspJipConsultingYearTt = initializer.configPreparedStatement("sql_getJnspJipConsultingYearTt", mapParam, conn_jnsp, null);

		stat_getJnspJipConsultingYearTb = initializer.configPreparedStatement("sql_getJnspJipConsultingYearTb", mapParam, conn_jnsp, null);
	}

	//-----ResultSet 객체에서 필드 값 설정 함수-----
	//ResultSet getJnspJipConsultingDay 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipConsultingDay() throws Exception{
		getJnspJipConsultingDay_BOARD_ID = GetB(getJnspJipConsultingDay.getString(1));
		getJnspJipConsultingDay_DAY = GetB(getJnspJipConsultingDay.getString(2));
		getJnspJipConsultingDay_CNT = getJnspJipConsultingDay.getLong(3);
	}

	//ResultSet getJnspJipConsultingDay 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipConsultingDay(){
		getJnspJipConsultingDay_BOARD_ID = "";
		getJnspJipConsultingDay_DAY = "";
		getJnspJipConsultingDay_CNT = 0L;
	}

	//ResultSet getJnspJipConsultingDay 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipConsultingDay() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipConsultingDay.getObject(1));
		row.add(getJnspJipConsultingDay.getObject(2));
		row.add(getJnspJipConsultingDay.getLong(3));

		return row;
	}

	//ResultSet getJnspJipConsultingDayTt 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipConsultingDayTt() throws Exception{
		getJnspJipConsultingDayTt_BOARD_ID = GetB(getJnspJipConsultingDayTt.getString(1));
		getJnspJipConsultingDayTt_DAY = GetB(getJnspJipConsultingDayTt.getString(2));
		getJnspJipConsultingDayTt_CNT = getJnspJipConsultingDayTt.getLong(3);
	}

	//ResultSet getJnspJipConsultingDayTt 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipConsultingDayTt(){
		getJnspJipConsultingDayTt_BOARD_ID = "";
		getJnspJipConsultingDayTt_DAY = "";
		getJnspJipConsultingDayTt_CNT = 0L;
	}

	//ResultSet getJnspJipConsultingDayTt 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipConsultingDayTt() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipConsultingDayTt.getObject(1));
		row.add(getJnspJipConsultingDayTt.getObject(2));
		row.add(getJnspJipConsultingDayTt.getLong(3));

		return row;
	}

	//ResultSet getJnspJipConsultingDayTb 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipConsultingDayTb() throws Exception{
		getJnspJipConsultingDayTb_BOARD_ID = GetB(getJnspJipConsultingDayTb.getString(1));
		getJnspJipConsultingDayTb_DAY = GetB(getJnspJipConsultingDayTb.getString(2));
		getJnspJipConsultingDayTb_CNT = getJnspJipConsultingDayTb.getLong(3);
	}

	//ResultSet getJnspJipConsultingDayTb 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipConsultingDayTb(){
		getJnspJipConsultingDayTb_BOARD_ID = "";
		getJnspJipConsultingDayTb_DAY = "";
		getJnspJipConsultingDayTb_CNT = 0L;
	}

	//ResultSet getJnspJipConsultingDayTb 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipConsultingDayTb() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipConsultingDayTb.getObject(1));
		row.add(getJnspJipConsultingDayTb.getObject(2));
		row.add(getJnspJipConsultingDayTb.getLong(3));

		return row;
	}

	//ResultSet getJnspJipConsultingMon 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipConsultingMon() throws Exception{
		getJnspJipConsultingMon_BOARD_ID = GetB(getJnspJipConsultingMon.getString(1));
		getJnspJipConsultingMon_DAY = GetB(getJnspJipConsultingMon.getString(2));
		getJnspJipConsultingMon_CNT = getJnspJipConsultingMon.getLong(3);
	}

	//ResultSet getJnspJipConsultingMon 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipConsultingMon(){
		getJnspJipConsultingMon_BOARD_ID = "";
		getJnspJipConsultingMon_DAY = "";
		getJnspJipConsultingMon_CNT = 0L;
	}

	//ResultSet getJnspJipConsultingMon 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipConsultingMon() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipConsultingMon.getObject(1));
		row.add(getJnspJipConsultingMon.getObject(2));
		row.add(getJnspJipConsultingMon.getLong(3));

		return row;
	}

	//ResultSet getJnspJipConsultingMonTt 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipConsultingMonTt() throws Exception{
		getJnspJipConsultingMonTt_BOARD_ID = GetB(getJnspJipConsultingMonTt.getString(1));
		getJnspJipConsultingMonTt_DAY = GetB(getJnspJipConsultingMonTt.getString(2));
		getJnspJipConsultingMonTt_CNT = getJnspJipConsultingMonTt.getLong(3);
	}

	//ResultSet getJnspJipConsultingMonTt 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipConsultingMonTt(){
		getJnspJipConsultingMonTt_BOARD_ID = "";
		getJnspJipConsultingMonTt_DAY = "";
		getJnspJipConsultingMonTt_CNT = 0L;
	}

	//ResultSet getJnspJipConsultingMonTt 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipConsultingMonTt() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipConsultingMonTt.getObject(1));
		row.add(getJnspJipConsultingMonTt.getObject(2));
		row.add(getJnspJipConsultingMonTt.getLong(3));

		return row;
	}

	//ResultSet getJnspJipConsultingMonTb 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipConsultingMonTb() throws Exception{
		getJnspJipConsultingMonTb_BOARD_ID = GetB(getJnspJipConsultingMonTb.getString(1));
		getJnspJipConsultingMonTb_DAY = GetB(getJnspJipConsultingMonTb.getString(2));
		getJnspJipConsultingMonTb_CNT = getJnspJipConsultingMonTb.getLong(3);
	}

	//ResultSet getJnspJipConsultingMonTb 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipConsultingMonTb(){
		getJnspJipConsultingMonTb_BOARD_ID = "";
		getJnspJipConsultingMonTb_DAY = "";
		getJnspJipConsultingMonTb_CNT = 0L;
	}

	//ResultSet getJnspJipConsultingMonTb 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipConsultingMonTb() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipConsultingMonTb.getObject(1));
		row.add(getJnspJipConsultingMonTb.getObject(2));
		row.add(getJnspJipConsultingMonTb.getLong(3));

		return row;
	}

	//ResultSet getJnspJipConsultingYear 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipConsultingYear() throws Exception{
		getJnspJipConsultingYear_BOARD_ID = GetB(getJnspJipConsultingYear.getString(1));
		getJnspJipConsultingYear_DAY = GetB(getJnspJipConsultingYear.getString(2));
		getJnspJipConsultingYear_CNT = getJnspJipConsultingYear.getLong(3);
	}

	//ResultSet getJnspJipConsultingYear 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipConsultingYear(){
		getJnspJipConsultingYear_BOARD_ID = "";
		getJnspJipConsultingYear_DAY = "";
		getJnspJipConsultingYear_CNT = 0L;
	}

	//ResultSet getJnspJipConsultingYear 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipConsultingYear() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipConsultingYear.getObject(1));
		row.add(getJnspJipConsultingYear.getObject(2));
		row.add(getJnspJipConsultingYear.getLong(3));

		return row;
	}

	//ResultSet getJnspJipConsultingYearTt 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipConsultingYearTt() throws Exception{
		getJnspJipConsultingYearTt_BOARD_ID = GetB(getJnspJipConsultingYearTt.getString(1));
		getJnspJipConsultingYearTt_DAY = GetB(getJnspJipConsultingYearTt.getString(2));
		getJnspJipConsultingYearTt_CNT = getJnspJipConsultingYearTt.getLong(3);
	}

	//ResultSet getJnspJipConsultingYearTt 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipConsultingYearTt(){
		getJnspJipConsultingYearTt_BOARD_ID = "";
		getJnspJipConsultingYearTt_DAY = "";
		getJnspJipConsultingYearTt_CNT = 0L;
	}

	//ResultSet getJnspJipConsultingYearTt 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipConsultingYearTt() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipConsultingYearTt.getObject(1));
		row.add(getJnspJipConsultingYearTt.getObject(2));
		row.add(getJnspJipConsultingYearTt.getLong(3));

		return row;
	}

	//ResultSet getJnspJipConsultingYearTb 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgetJnspJipConsultingYearTb() throws Exception{
		getJnspJipConsultingYearTb_BOARD_ID = GetB(getJnspJipConsultingYearTb.getString(1));
		getJnspJipConsultingYearTb_DAY = GetB(getJnspJipConsultingYearTb.getString(2));
		getJnspJipConsultingYearTb_CNT = getJnspJipConsultingYearTb.getLong(3);
	}

	//ResultSet getJnspJipConsultingYearTb 객체의 필드 값 초기화 함수
	private void setFieldInitFromgetJnspJipConsultingYearTb(){
		getJnspJipConsultingYearTb_BOARD_ID = "";
		getJnspJipConsultingYearTb_DAY = "";
		getJnspJipConsultingYearTb_CNT = 0L;
	}

	//ResultSet getJnspJipConsultingYearTb 객체에서 RowData 획득함수
	private List<Object> getAIRowDataFromgetJnspJipConsultingYearTb() throws Exception{
		List<Object> row = new ArrayList<Object>();

		row.add(getJnspJipConsultingYearTb.getObject(1));
		row.add(getJnspJipConsultingYearTb.getObject(2));
		row.add(getJnspJipConsultingYearTb.getLong(3));

		return row;
	}

	//-----고정 데이터 초기화 함수-----
	private void initConstVarientEx(){
	}

	//----AI_CHART_OBJ41 챠트 데이터 함수----
	private void getChartDataAI_CHART_OBJ41( ) throws Exception{
		//DataSet 객체 생성
		//ResultSet getJnspJipConsultingYear 객체의 생성
		if(getJnspJipConsultingYear==null){
			getJnspJipConsultingYear = stat_getJnspJipConsultingYear.executeQuery();
		}else{
			getJnspJipConsultingYear.beforeFirst();
		}
		if(!getJnspJipConsultingYear.isBeforeFirst()){		//생성된 ResultSet에 레코드가 없으면
			return;
		}

		//계열(Series) 필드 설정
		AI_CHART_OBJ41="\t";
		AI_CHART_OBJ41=AI_CHART_OBJ41 + "CNT\r\n";

		while(getJnspJipConsultingYear.next()){   //데이터 루프문
			//데이터 fetch
			setFieldVariableFromgetJnspJipConsultingYear();   //RecordSet getJnspJipConsultingYear에서 필드 값 설정

			//X축 레이블 필드 설정
			AI_CHART_OBJ41=AI_CHART_OBJ41 + getJnspJipConsultingYear_DAY + "\t";

			//데이터 설정
			AI_CHART_OBJ41=AI_CHART_OBJ41 + getJnspJipConsultingYear_CNT + "\r\n";
		}   //while end
	}

	//-----공통 함수 선언-----
	//파라미터 설정 함수
	private void setParam() {
		//SetParam_AutoCode
		reportMode=decoder.getParameterB("reportMode");
		if(reportMode.equals("")) {
			reportMode="HTML";
		}
		manager.setParam("pdfFilename:" + pdfFilename + "," + "excelFilename:" + excelFilename + "," + decoder.getParameterB("reportParams"));

		//char data[] = {0x14};
		//String str = new String(data);
		mapParam = new HashMap<String, String>();

		userIdx_Param=decoder.getParameterB("userIdx");
		//userIdx_Param=aiReplace(userIdx_Param, str, "\n");
		mapParam.put("userIdx", userIdx_Param);

		Idx_Param=decoder.getParameterB("Idx");
		//Idx_Param=aiReplace(Idx_Param, str, "\n");
		mapParam.put("Idx", Idx_Param);
	}

	//상수 데이터 초기화 래퍼 함수
	private void initConstVarient() {
		//InitConstVarient_AutoCode
		initConstVarientEx();
	}

	//배경 이미지 출력 래퍼 함수
	private void getBgImageScript(int nIndex) throws Exception{
		//GetBgImageScript_AutoCode
		getBgImageScriptEx(nIndex);
	}

	//페이지 스킵 함수
	//페이지 스킵시 호출되는 함수로서 페이지 번호를 증가시키고 페이지 지시문 출력 그리고 Y좌표 초기화
	//매개변수에 따라 해당 쉬트의 배경 이미지, 머리글 밴드, 바닥글 밴드 함수 호출
	private void pageSkip(int nIndex) throws Exception{
		//PageSkip_AutoCode
		if(nBandRepeatType==1) {
			int tmpX;
			tmpX=nXCurPos+nBandWidth+nBandOffset;
			nHorRepeatCnt=nHorRepeatCnt+1;
			if(tmpX+nBandWidth>nXEndPos || nHorRepeatCnt==nHorRepeatNum) {
				nYBandStart=nYStartPos;
				nYBandEnd=0;
				nHorRepeatCnt=0;
			}else{
				if(nYBandEnd<nYCurPos) {
					nYBandEnd=nYCurPos;
				}
				nYCurPos=nYBandStart;
				nXCurPos=tmpX;
				return;
			}
		}

		nXCurPos=nXStartPos;
		nYCurPos=nYStartPos;
		nPageNum=nPageNum+1;
		pageWrite(nPageNum);

		switch(nIndex){
			case 10:		//SHEET=Sheet=1   FRAME=0에서 페이지 스킵시
			break;
		}
	}

	//페이지 스킵이 필요한지 검사하는 함수
	private boolean isPageSkip(int nTestPos){
		//IsPageSkip_AutoCode
		if(nTestPos>nYEndPos){
			return true;
		}else{
			return false;
		}
	}

	//문자의 폭을 조사하여 데이터의 출력 높이를 자동적으로 조정하는 함수
	private int getPrintHeight(String data, int[] charWidth, int fontSize, int printWidth, int printHeight, int nMaxHeight, int horMargin, int vertMargin, String styleName) throws Exception {
		//GetPrintHeight_AutoCode
		if(data.equals(isEmpty)){
			return nMaxHeight;
		}
		if(!reportMode.equals("AIScript")) {
			printWidth+=horMargin;
			printHeight+=vertMargin;
			int needHeight=(int)TextHandler.wordWrapTextEx(printWidth, data, styleName, manager.getAIStyleInfo());

			if(needHeight>printHeight) {
				needHeight=needHeight-printHeight;
			}else{
				needHeight=0;
			}

			needHeight=(int)MAX((long)needHeight,(long)nMaxHeight);
			return needHeight;
		}
		else {
			int ch;
			int len = 95;
			int []width = new int[1];
			width[0] = 0;
			int asciiWidth = 0;
			int linePitch = (int)(fontSize*1.4);
			int height = linePitch;
			int size = data.length();
			int ascIndex=0;
			printWidth = printWidth*100;

			for (int i = 0; i < size; i++) {
				ch = data.charAt(i);

				if(ch<32 && !(ch==10 || ch==20 || ch==13)){
					continue;
				}

				if((ch>64 && ch<91) || (ch>96 && ch<123)) {
					if(asciiWidth==0){
						ascIndex=i;
					}

					asciiWidth += charWidth[ch-32];
					if (i==size-1){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i+1, linePitch, printWidth, width, asciiWidth);
					}
				} else if (ch==10 || ch==20 || ch==13) {
					if(asciiWidth>0){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i, linePitch, printWidth, width, asciiWidth);
						asciiWidth = 0;
					}

					width[0] = 0;
					height += linePitch;

					if (ch==13) {
						if ((i != size-1) && (10 == (int)data.charAt(i+1))) {
							i++;
						}
					}
				} else {
					if(asciiWidth>0){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i, linePitch, printWidth, width, asciiWidth);
						asciiWidth=0;
					}

					if(ch>=32 && ch<=127){
						width[0] += charWidth[ch-32];
						if (width[0] > printWidth) {
							if (ch==32)
							{
								width[0] = 0;
							}
							else
							{
								width[0] = charWidth[ch-32];
							}
							height += linePitch;
						}
					}else{
						width[0] += charWidth[len];
						if (width[0] > printWidth) {
							width[0] = charWidth[len];
							height += linePitch;
						}
					}
				}
			}

			if (height>printHeight) {
				height=height-printHeight;
			}else{
				height=0;
			}

			height = (int)MAX((long)height,(long)nMaxHeight);
			return height;
		}
	}

	//영문 단어의 폭을 문자별로 조사하여 데이터의 출력 높이를 조정하는 함수
	private int getWordWrapHeight(String data, int[] charWidth, int nStartIndex, int nEndIndex, int linePitch, int printWidth, int []width, int asciiWidth){
		//GetWordWrapHeight_AutoCode
		int ch;
		int height=0;

		if(asciiWidth>printWidth){
			for(int i=nStartIndex; i<nEndIndex; i++){
				ch=data.charAt(i);
				width[0]+=charWidth[ch-32];
				if(width[0]>printWidth){
					width[0]=charWidth[ch-32];
					height+=linePitch;
				}
			}
		}else{
			width[0]+=asciiWidth;
			if(width[0]>printWidth){
				width[0]=asciiWidth;
				height+=linePitch;
			}
		}

		return height;
	}

	//문자의 폭을 조사하여 데이터의 출력 높이를 자동적으로 조정하고 페이지 초과시 초과하는 데이터 절삭하는 함수
	private int getPrintHeightEx(String data, String[] strSplitData, int[] charWidth, int fontSize, int printWidth, int nExtHeight, int nMaxHeight, int horMargin, int vertMargin, String styleName) throws Exception {
		//GetPrintHeightEx_AutoCode
		if(!reportMode.equals("AIScript")) {
			strSplitData[0]="";
			strSplitData[1]="";
			printWidth+=horMargin;
			nExtHeight+=vertMargin;
			int needHeight=(int)TextHandler.wordWrapTextEx(printWidth, nExtHeight, data, strSplitData, styleName, manager.getAIStyleInfo());

			if(needHeight>nExtHeight) {
				needHeight=nExtHeight;
			}

			needHeight = (int)MAX((long)needHeight,(long)nMaxHeight);
			return needHeight;
		}
		else {
			int ch;
			int i;
			int len = 95;
			int []width = new int[1];
			width[0] = 0;
			int asciiWidth = 0;
			int linePitch = (int)(fontSize*1.4);
			int height = linePitch;
			int size = data.length();
			int ascIndex=0;
			boolean bSplit=false;
			strSplitData[0]="";
			strSplitData[1]="";
			printWidth = printWidth*100;

			for (i = 0; i < size; i++) {
				ch = data.charAt(i);

				if(ch<32 && !(ch==10 || ch==20 || ch==13)){
					continue;
				}

				if ((ch>64 && ch<91) || (ch>96 && ch<123)) {
					if(asciiWidth==0){
						ascIndex=i;
					}

					asciiWidth += charWidth[ch-32];
					if (i==size-1){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i+1, linePitch, printWidth, width, asciiWidth);
						if(height>nExtHeight){
							height=nExtHeight;
							bSplit=true;
							i=ascIndex;
							break;
						}
					}
				}else if (ch==10 || ch==20 || ch==13) {
					if(asciiWidth>0){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i, linePitch, printWidth, width, asciiWidth);
						if(height>nExtHeight){
							height=nExtHeight;
							bSplit=true;
							i=ascIndex;
							break;
						}
						asciiWidth = 0;
					}

					width[0] = 0;
					height += linePitch;
					if (ch==13){
						if ((i != size-1) && (10 == (int)data.charAt(i+1))) {
							i++;
						}
					}

					if(height>nExtHeight){
						height=nExtHeight;
						if(i!=size-1){
							bSplit=true;
							i++;
						}
						break;
					}
				}else{
					if(asciiWidth>0){
						height+=getWordWrapHeight(data, charWidth, ascIndex, i, linePitch, printWidth, width, asciiWidth);
						if(height>nExtHeight){
							height=nExtHeight;
							bSplit=true;
							i=ascIndex;
							break;
						}
						asciiWidth=0;
					}

					if(ch>=32 && ch<=127){
						width[0] += charWidth[ch-32];
						if (width[0] > printWidth) {
							if (ch==32)
							{
								width[0] = 0;
							}
							else
							{
								width[0] = charWidth[ch-32];
							}
							height += linePitch;
						}
					}else{
						width[0] += charWidth[len];
						if (width[0] > printWidth) {
							width[0] = charWidth[len];
							height += linePitch;
						}
					}

					if(height>nExtHeight){
						height=nExtHeight;
						bSplit=true;
						break;
					}
				}
			}

			if(bSplit){
				strSplitData[0]=data.substring(0, i);
				strSplitData[1]=data.substring(i);
			}

			height = (int)MAX((long)height,(long)nMaxHeight);
			return height;
		}
	}

	//스크립트 헤더 출력 함수
	private void getScriptHeader(String paper, String size, String value, String orient, String margin) throws Exception{
		//GetScriptHeader_AutoCode
		manager.scriptWrite("AIReport", "scriptVersion|docVersion|style|title", "32|0|Temporary.style|통계", false);
	}

	private void getSheetPaperInfo(String paper, String size, String value, String orient, String margin) throws Exception{
		//GetSheetPaperInfo_AutoCode
		manager.scriptWrite("PaperInfo", "name|size|value|orientation|margin", paper+"|"+size+"|"+value+"|"+orient+"|"+margin, true);
	}

	private void initSheetVariant(int constStartX, int constStartY, int constEndX, int constEndY, boolean bFirstFrame){
		//InitSheetVariant_AutoCode
		if(bFirstFrame){
			nStartPage=nMaxPage+1;
			nYLastPos=0;
		}
		nPageNum=nStartPage;
		nYStartPos=constStartY;
		nYEndPos=constEndY;
		nYCurPos=nYStartPos;
		nXStartPos=constStartX;
		nXEndPos=constEndX;
		CELL_OBJECT=0;
		DRAW_OBJECT=1;
		nXCurPos=nXStartPos;
	}

	private void initChildSheetVariant(int constStartX, int constStartY, int constEndX, int constEndY, boolean bIsMultiFrame, boolean bIsFirstFrame){
		//InitChildSheetVariant_AutoCode
		nXStartPos=constStartX;
		nXEndPos=constEndX;
		nXCurPos=nXStartPos;
		nYStartPos=constStartY;
		nYEndPos=constEndY;

		if(bIsMultiFrame){
			if(bIsFirstFrame){
				nStartPage=nPageNum;
				nYSavePos=nYCurPos;
				nYLastPos=0;
			}else{
				nPageNum=nStartPage;
				nYCurPos=nYSavePos;
			}
		}else{
			nStartPage=nPageNum;
		}
	}

	//Empty Row만으로 구성되어 출력 위치를 조정하기 위한 VoidBand 함수
	//nRangePos - VoidBand의 출력 영역
	//nIndex - PageSkip 함수 호출시 전달할 쉬트 인덱스
	private boolean voidBandNoneData(int nRangePos, int nIndex) throws Exception{
		//VoidBandNoneData_AutoCode
		int nTestPos;
		nTestPos=nYCurPos+nRangePos;
		if(isPageSkip(nTestPos)){
			pageSkip(nIndex);
			return true;
		}else{
			nYCurPos=nYCurPos+nRangePos;
			return false;
		}
	}

	private String Get0(String str){
		//Get0_AutoCode
		if(str==null){
			return "0";
		}else{
			if(str.equals("")){
				return "0";
			}else{
				return str;
			}
		}
	}

	private String GetB(String str){
		//GetB_AutoCode
		if(str==null){
			return "";
		}else{
			return str;
		}
	}

	private double SUM(double accVal, double tmpVal){
		//SUM(double, double)_AutoCode
		return(accVal+tmpVal);
	}

	private double SUM(double accVal, long tmpVal){
		//SUM(double, long)_AutoCode
		return(accVal+(double)tmpVal);
	}

	private long SUM(long accVal, long tmpVal){
		//SUM(long, long)_AutoCode
		return(accVal+tmpVal);
	}

	private double SUM(long accVal, double tmpVal){
		//SUM(long, double)_AutoCode
		return((double)accVal+tmpVal);
	}

	private long COUNT(long accuCNT){
		//COUNT_AutoCode
		return ++accuCNT;
	}

	private long MIN(long maxV, long maxTempV){
		//MIN(long, long)_AutoCode
		if(maxV<=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MIN(long maxV, double maxTempV){
		//MIN(long, double)_AutoCode
		if((double)maxV<=maxTempV){return (double)maxV;}
		else{return maxTempV;}
	}

	private double MIN(double maxV, double maxTempV){
		//MIN(double, double)_AutoCode
		if(maxV<=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MIN(double maxV, long maxTempV){
		//MIN(double, long)_AutoCode
		if(maxV<=maxTempV){return maxV;}
		else{return (double)maxTempV;}
	}

	private long MAX(long maxV, long maxTempV){
		//MAX(long, long)_AutoCode
		if(maxV>=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MAX(long maxV, double maxTempV){
		//MAX(long, double)_AutoCode
		if((double)maxV>=maxTempV){return (double)maxV;}
		else{return maxTempV;}
	}

	private double MAX(double maxV, double maxTempV){
		//MAX(double, double)_AutoCode
		if(maxV>=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MAX(double maxV, long maxTempV){
		//MAX(double, long)_AutoCode
		if(maxV>=maxTempV){return maxV;}
		else{return (double)maxTempV;}
	}

	private double AVG(double sumVal, long cntVal){
		//AVG(double, long)_AutoCode
		return(sumVal/cntVal);
	}

	private double AVG(long sumVal, long cntVal){
		//AVG(long, long)_AutoCode
		return((double)sumVal/(double)cntVal);
	}

	private String aiReplace(String strAll, String strSrc, String strDest) {
		//AIReplace_AutoCode
		int st = 0, ed = 0;
		final int size = strAll.length();
		ed = strAll.indexOf(strSrc);
		if (ed == -1) return strAll;

		StringBuffer buf = new StringBuffer(size);
		final int len =  strSrc.length();
		do {
			buf.append(strAll.substring(st, ed));
			buf.append(strDest);
			ed += len;
			st = ed;
		} while ((ed = strAll.indexOf(strSrc, ed)) != -1);
		if (st < size) {
			buf.append(strAll.substring(st));
		}
		return buf.toString();
	}

	private String toDate() {
		//ToDate_AutoCode
		SimpleDateFormat dateFormat=new SimpleDateFormat("'#SERVERDATE#'yyyy/MM/dd/HH/mm/ss");
		java.util.Date currentDate = new java.util.Date();
		return dateFormat.format(currentDate);
	}

	final String toKor (String en){
		//ToKor_AutoCode
		if(en==null){
			return "";
		}
		try{
			return new String(en.getBytes("ISO-8859-1"), "utf-8");
		}catch(Exception e){return en;}
	}

	private void objectWrite(int type, int left, int top, int width, int height, String data, String name, String style) throws Exception {
		//ObjectWrite_AutoCode
		manager.scriptWrite(type, left, top, width, height, data, name, style);
	}

	private void propertyWrite(int type, String name, String property, String style) throws Exception {
		//PropertyWrite_AutoCode
		manager.scriptWrite(type, name, property, style);
	}

	private void pageWrite(int pageNum) throws Exception {
		//PageWrite_AutoCode
		manager.scriptWrite("Page", "number", Integer.toString(pageNum), true);
	}

	private void objectCellWrite(String name, String data, int nMoveX, int nMoveY) throws Exception {
		objectWrite(CELL_OBJECT, nMoveX+(nXCurPos+mapLeft.get(name)), nMoveY+(nYCurPos+mapTop.get(name)), mapWidth.get(name), mapHeight.get(name), data, name, mapStyle.get(name));
	}

	public String checkParam(String param) {
		param = param.replace("'", "");
		param = param.replace(";", "");
		param = param.replace("|", "");
		param = param.replace(":", "");
		param = param.replace("+", "");
		param = param.replace("\"", "");
		param = param.replace("\\", "");
		param = param.replace("--", "");
		param = param.replace("/", "");
		param = param.replaceAll("(?i)select", "");
		param = param.replaceAll("(?i)union", "");
		param = param.replaceAll("(?i)delete", "");
		param = param.replaceAll("(?i)update", "");
		param = param.replaceAll("(?i)insert", "");
		param = param.replaceAll("(?i)create", "");
		param = param.replaceAll("(?i)alter", "");
		param = param.replaceAll("(?i)drop", "");
		param = param.replaceAll("(?i)grant", "");
		param = param.replaceAll("(?i)revoke", "");
		param = param.replaceAll("(?i)merge", "");
		return param;
	}

	public String checkAITag(String strText) {
		strText = strText.replace("AI{P}", "^");
		strText = strText.replace("AI{F}", "@");
		strText = strText.replace("AI{S}", "#");
		strText = strText.replace("AI{E}", "=");
		return strText;
	}

	//셀 Rect, Style값 Map 저장
	public void setCellInfoMap_Internal(String name, int left, int top, int width, int height, String style) throws Exception {
		if( left != -1 ) {
			mapLeft.put(name, left);
		}
		if( top != -1 ) {
			mapTop.put(name, top);
		}
		if( width != -1 ) {
			mapWidth.put(name, width);
		}
		if( height != -1 ) {
			mapHeight.put(name, height);
		}
		if( style != null && !style.equals("") ) {
			mapStyle.put(name, style);
		}
	}

	//셀 Rect, Style값 저장
	public void setCellInfoMap() throws Exception {
		mapLeft = new HashMap<String, Integer>();
		mapTop = new HashMap<String, Integer>();
		mapWidth = new HashMap<String, Integer>();
		mapHeight = new HashMap<String, Integer>();
		mapStyle = new HashMap<String, String>();
		setCellInfoMap_Internal("sheet10_A1", 0, 0, 24, 20, "cell_style_0");
		setCellInfoMap_Internal("sheet10_A2", 0, 0, 256, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_J2", 256, 0, 29, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_K2", 285, 0, 29, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_L2", 314, 0, 29, 27, "cell_style_2");
		setCellInfoMap_Internal("sheet10_M2", 343, 0, 29, 27, "cell_style_2");
		setCellInfoMap_Internal("sheet10_N2", 372, 0, 29, 27, "cell_style_2");
		setCellInfoMap_Internal("sheet10_O2", 401, 0, 29, 27, "cell_style_2");
		setCellInfoMap_Internal("sheet10_P2", 430, 0, 29, 27, "cell_style_2");
		setCellInfoMap_Internal("sheet10_Q2", 459, 0, 28, 27, "cell_style_2");
		setCellInfoMap_Internal("sheet10_R2", 487, 0, 28, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_S2", 515, 0, 28, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_T2", 543, 0, 28, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_U2", 571, 0, 28, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_V2", 599, 0, 28, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_W2", 627, 0, 28, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_X2", 655, 0, 28, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_Y2", 683, 0, 28, 27, "cell_style_1");
		setCellInfoMap_Internal("sheet10_B22", 24, 0, 348, 20, "cell_style_4");
		setCellInfoMap_Internal("sheet10_N22", 372, 0, 339, 20, "cell_style_5");
		setCellInfoMap_Internal("sheet10_B23", 24, 0, 348, 20, "cell_style_6");
		setCellInfoMap_Internal("sheet10_N23", 372, 0, 339, 20, "cell_style_7");
		setCellInfoMap_Internal("sheet10_B24", 24, 0, 29, 20, "cell_style_8");
	}

	private ResultSet acquireResultSet(CallableStatement cstmt, int cursorIdx) throws SQLException {
		if (cstmt.execute()) {
			if (cursorIdx == -1) {
				return (cstmt.getResultSet());
			} else {
				return ((ResultSet) cstmt.getObject(cursorIdx));
			}
		} else {
			int count;
			if ((count = cstmt.getUpdateCount()) == -1) {
				if (cursorIdx == -1) {
					throw (new UnsupportedOperationException("None result"));
				} else {
					return ((ResultSet) cstmt.getObject(cursorIdx));
				}
			}
			while (true) {
				if (cstmt.getMoreResults()) {
					if (cursorIdx == -1) {
						return (cstmt.getResultSet());
					} else {
						return ((ResultSet) cstmt.getObject(cursorIdx));
					}
				} else if ((count = cstmt.getUpdateCount()) == -1) {
					if (cursorIdx == -1) {
						throw (new UnsupportedOperationException("None result-2"));
					} else {
						return ((ResultSet) cstmt.getObject(cursorIdx));
					}
				}
			}
		}
	}
}
%>
